### ISSUE TITLE
Cannot find opencv=2.4.13.4 on windows

### ISSUE THREAD

**Issue by crousseau** [conda-forge/opencv-feedstock#103]
Hi,
I need opencv 2.4.13.4 compiled with ffmpeg support (see: [issue 88](https://github.com/conda-forge/opencv-feedstock/issues/88)) for my software to run on windows  but it is not available.

`conda search -c conda-forge opencv`
gives only 2.4.13 np113py27_1 with checksum 06a363cc26d...

It works fine on MacOS and Linux
Is there any plan to compile and distribute 2.4.13.4 for windows ?

Thanks

**Comment by jakirkham** [comment]
Unfortunately we cannot proceed here. OpenCV only supports Python 2.7. However Python 2.7 on Windows requires Visual Studio 2008 be used. Though upstream has no interest in supporting Visual Studio 2008 as noted in issue ( https://github.com/opencv/opencv/issues/8481 ). So we no longer support Windows builds of OpenCV 2.
