### ISSUE TITLE
Problems Installing OPENCV on a Mac Pro (desktop) running Python 3.6.x under the Anaconda Distribution

### ISSUE THREAD

**Issue by OrbitalMechanic** [conda-forge/opencv-feedstock#108]
I'm attempting to install OPENCV on a Mac Pro Late 2013) running Mac OS X Sierra (10.12.6) under the Anaconda Distribution for Python 3.6.x. In installing POENCV I used the command,

conda install -c conda-forge opencv

Furthermore, I had to update ffmpeg using the command

                                             conda update ffmpeg

In running the demo program (attached to this posting as demo.py.txt)

                                            import cv2
                                            print("OpenCV version:")
                                            print(cv2.__version__)
                                            img = cv2.imread("clouds.jpg")
                                            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                                            cv2.imshow("Over the Clouds", img)
                                            cv2.imshow("Over the Clouds - gray", gray)
                                            cv2.waitKey(0)
                                            cv2.destroyAllWindows()

The response that I get is can be found in the attached file, demo.txt.

Any suggestions?

Please advise.

Sam Dupree

[demo.py.txt](https://github.com/conda-forge/opencv-feedstock/files/1805046/demo.py.txt)

[demo.txt](https://github.com/conda-forge/opencv-feedstock/files/1805041/demo.txt)

**Comment by hajapy** [comment]
This is probably due to mixing packages from conda-forge and defaults.
