### ISSUE TITLE
ImportError: libx264.so.138: cannot open shared object file

### ISSUE THREAD

**Issue by akorosov** [conda-forge/opencv-feedstock#115]
Hi!
Thank you for maintaining the feedstock for opencv!
I have troubles installing opencv 3 from conda-forge channel.

Here is what i do:
```
conda create -n py3djocv opencv -c conda-forge
conda activate py3djocv
```
The error:
```
(py3djocv) project> python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libx264.so.138: cannot open shared object file: No such file or directory
```
conda-info output:
```
     active environment : py3djocv
    active env location : /home/user/miniconda3/envs/py3djocv
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.5.8
    conda-build version : 3.10.9
         python version : 3.6.3.final.0
       base environment : /home/user/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/user/miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.8 requests/2.18.4 CPython/3.6.3 Linux/4.15.0-24-generic ubuntu/16.04 glibc/2.23
                UID:GID : 10147:15001
             netrc file : None
           offline mode : False
```

conda-list output:
```
# packages in environment at /home/user/miniconda3/envs/py3djocv:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
ffmpeg                    3.2.4                         3    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                h470a237_0    conda-forge
glib                      2.55.0                        0    conda-forge
graphite2                 1.3.11               hfc679d8_0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
harfbuzz                  1.7.6                         0    conda-forge
hdf5                      1.10.1                        2    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
jasper                    1.900.1                       4    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libiconv                  1.15                 h470a237_1    conda-forge
libpng                    1.6.34               ha92aebf_1    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he6b73bb_1    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13                 h470a237_1    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.14.5          py36_blas_openblashd3ea46f_201  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
opencv                    3.4.1           py36_blas_openblas_200  [blas_openblas]  conda-forge
openssl                   1.0.2o                        0    conda-forge
pcre                      8.41                          1    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
python                    3.6.5                         1    conda-forge
qt                        5.6.2                         7    conda-forge
readline                  7.0                           0    conda-forge
setuptools                40.0.0                   py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
wheel                     0.31.1                   py36_0    conda-forge
x264                      20180712             h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_5    conda-forge
xorg-libxdmcp             1.1.2                h470a237_6    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

the list of libx264 files:
```
(py3djocv) project> find /home/user/miniconda3/envs/py3djocv/ -name libx264.so*
/home/user/miniconda3/envs/py3djocv/lib/libx264.so.152
/home/user/miniconda3/envs/py3djocv/lib/libx264.so
```

Please help to make it work! Thank you!

**Comment by akorosov** [comment]
The workaround is to pin down the version:
`x264=20131218`
Can you maybe specify that in the recipe?

**Comment by sdvillal** [comment]
This should now be fixed. Please try and close if it is the case (or let us know if it is still failing).

**Comment by akorosov** [comment]
Thank you!

**Comment by vhcandido** [comment]
I'm having exactly the same issue. Same steps and results mentioned by @akorosov , `libx264.so.152` is located in the library directory of the current environment and Python fails to fin `libx264.so.152`.

**Comment by sdvillal** [comment]
No error for me if I run the same commands, so you should be doing something different. Are you creating your environment from scratch?

**Comment by vhcandido** [comment]
@sdvillal You're actually right, I was installing opencv in an environment created from another one, so if in a new environment I run `conda install -c conda-forge opencv` it does work.

I also tried installing opencv right after numpy, matplotlib, jupyter and it worked too.
Thank you!

I don't know what caused that exactly but, in the issue I mentioned, when I tried to install `opencv` I got
```
    opencv:           3.4.1-py36h6fd60c2_3
```
instead of
```
    opencv:           3.4.1-py36_blas_openblash829a850_201  conda-forge [blas_openblas]
```
and then the solution suggested previously by @akorosov did it.

**Comment by hillierdani** [comment]
Thanks for the hints! I had the same issue, opencv was installed via the loopbio channel. Uninstalled opencv and did conda install -c conda-forge opencv solved the issue.

**Comment by Ranjan0189** [comment]
Thanks to all, it's also worked for me.

**Comment by techsci81** [comment]
> The workaround is to pin down the version:
> `x264=20131218`
> Can you maybe specify that in the recipe?

Could you please show how to do it? I also have same error:
ImportError: libx264.so.138: cannot open shared object file: No such file or directory

out put for conda info:
(ocv) sv@sv:~$ conda info

     active environment : ocv
    active env location : /home/sv/anaconda3/envs/ocv
            shell level : 2
       user config file : /home/sv/.condarc
 populated config files : /home/sv/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.23
       base environment : /home/sv/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/sv/anaconda3/pkgs
                          /home/sv/.conda/pkgs
       envs directories : /home/sv/anaconda3/envs
                          /home/sv/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/4.15.0-96-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
out put for conda list
(ocv) sv@sv:~$ conda list
# packages in environment at /home/sv/anaconda3/envs/ocv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
blas                      1.1                    openblas    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2018.8.24             py35_1001    conda-forge
ffmpeg                    3.4.1                         0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freeglut                  3.0.0             hf484d3e_1005    conda-forge
freetype                  2.7                           1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.51.4                        0    conda-forge
harfbuzz                  1.3.4                         2    conda-forge
hdf5                      1.8.18                        3    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
jasper                    2.0.14               habb8e15_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran               3.0.0                         1    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.0.6                         5    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.3                         6    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.12.1          py35_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
opencv                    3.2.0           np112py35_blas_openblas_203  [blas_openblas]  conda-forge
openssl                   1.0.2u               h516909a_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.5.1                         1    conda-forge
readline                  6.2                           0    conda-forge
setuptools                40.4.3                   py35_0    conda-forge
sqlite                    3.9.2                         0    conda-forge
tk                        8.5.19                        2    conda-forge
wheel                     0.34.2                     py_1    conda-forge
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.0.5                         1    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

locating the lib file that was causing the problem:
(ocv) sv@sv:~$ find /home/sv/anaconda3/envs/ocv -name libx264.so*
/home/sv/anaconda3/envs/ocv/lib/libx264.so
/home/sv/anaconda3/envs/ocv/lib/libx264.so.152

the library is present but why i am getting error?

**Comment by hmaarrfk** [comment]
opencv 3.2 is very old.

please try to install a more updated version of 3.4 or 4.x, both of which we support.

if you have trouble installing those, please open a new issue

**Comment by VincentChong123** [comment]
@akorosov ,

> The workaround is to pin down the version:
> `x264=20131218`
it works for opencv 3.4.1. Thanks
conda install ffmpeg x264=20131218 -c conda-forge
