### ISSUE TITLE
 ISO C++1z does not allow dynamic exception specifications

### ISSUE THREAD

**Issue by piperod** [conda-forge/opencv-feedstock#119]
Issue: I'm getting this error when trying to install the recipe: 
 ISO C++1z does not allow dynamic exception specifications

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by hajapy** [comment]
Without more details or steps to reproduce it's not possible for us to help you debug this issue or identify if it is a conda-forge specific issue.

**Comment by piperod** [comment]
This is part of the log where the error is shown, 

[  0%] Building CXX object modules/freetype/CMakeFiles/opencv_freetype_pch_dephelp.dir/opencv_freetype_pch_dephelp.cxx.o
[  0%] Building CXX object modules/xobjdetect/CMakeFiles/opencv_xobjdetect_pch_dephelp.dir/opencv_xobjdetect_pch_dephelp.cxx.o
[  0%] Building C object 3rdparty/ittnotify/CMakeFiles/ittnotify.dir/src/ittnotify/ittnotify_static.c.o
[  0%] Building CXX object modules/reg/CMakeFiles/opencv_reg_pch_dephelp.dir/opencv_reg_pch_dephelp.cxx.o
[  0%] Building CXX object modules/plot/CMakeFiles/opencv_plot_pch_dephelp.dir/opencv_plot_pch_dephelp.cxx.o
[  0%] Building CXX object modules/text/CMakeFiles/opencv_text_pch_dephelp.dir/opencv_text_pch_dephelp.cxx.o
[  0%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn_pch_dephelp.dir/opencv_dnn_pch_dephelp.cxx.o
[  1%] Building CXX object modules/hdf/CMakeFiles/opencv_hdf_pch_dephelp.dir/opencv_hdf_pch_dephelp.cxx.o
[  1%] Building CXX object modules/dpm/CMakeFiles/opencv_dpm_pch_dephelp.dir/opencv_dpm_pch_dephelp.cxx.o
[  1%] Built target gen-pkgconfig
[  1%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_core.c.o
[  1%] Building CXX object modules/img_hash/CMakeFiles/opencv_img_hash_pch_dephelp.dir/opencv_img_hash_pch_dephelp.cxx.o
[  1%] Building CXX object modules/hfs/CMakeFiles/opencv_hfs_pch_dephelp.dir/opencv_hfs_pch_dephelp.cxx.o
[  1%] Building CXX object modules/ccalib/CMakeFiles/opencv_ccalib_pch_dephelp.dir/opencv_ccalib_pch_dephelp.cxx.o
[  1%] Building C object 3rdparty/ittnotify/CMakeFiles/ittnotify.dir/src/ittnotify/jitprofiling.c.o
[  1%] Building CXX object modules/dnn_objdetect/CMakeFiles/opencv_dnn_objdetect_pch_dephelp.dir/opencv_dnn_objdetect_pch_dephelp.cxx.o
[  1%] Building CXX object modules/ml/CMakeFiles/opencv_ml_pch_dephelp.dir/opencv_ml_pch_dephelp.cxx.o
[  1%] Building CXX object modules/phase_unwrapping/CMakeFiles/opencv_phase_unwrapping_pch_dephelp.dir/opencv_phase_unwrapping_pch_dephelp.cxx.o
[  1%] Building CXX object modules/objdetect/CMakeFiles/opencv_objdetect_pch_dephelp.dir/opencv_objdetect_pch_dephelp.cxx.o
[  1%] Linking CXX static library ../../lib/libopencv_reg_pch_dephelp.a
[  1%] Building CXX object modules/surface_matching/CMakeFiles/opencv_surface_matching_pch_dephelp.dir/opencv_surface_matching_pch_dephelp.cxx.o
[  1%] Building CXX object modules/core/CMakeFiles/opencv_core_pch_dephelp.dir/opencv_core_pch_dephelp.cxx.o
[  1%] Building CXX object modules/fuzzy/CMakeFiles/opencv_fuzzy_pch_dephelp.dir/opencv_fuzzy_pch_dephelp.cxx.o
[  1%] Building CXX object modules/superres/CMakeFiles/opencv_superres_pch_dephelp.dir/opencv_superres_pch_dephelp.cxx.o
[  1%] Building CXX object modules/imgcodecs/CMakeFiles/opencv_imgcodecs_pch_dephelp.dir/opencv_imgcodecs_pch_dephelp.cxx.o
[  1%] Building CXX object modules/video/CMakeFiles/opencv_video_pch_dephelp.dir/opencv_video_pch_dephelp.cxx.o
[  1%] Building CXX object modules/bioinspired/CMakeFiles/opencv_bioinspired_pch_dephelp.dir/opencv_bioinspired_pch_dephelp.cxx.o
[  1%] Building CXX object modules/shape/CMakeFiles/opencv_shape_pch_dephelp.dir/opencv_shape_pch_dephelp.cxx.o
[  2%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc_pch_dephelp.dir/opencv_imgproc_pch_dephelp.cxx.o
[  2%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui_pch_dephelp.dir/opencv_highgui_pch_dephelp.cxx.o
[  3%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d_pch_dephelp.dir/opencv_calib3d_pch_dephelp.cxx.o
[  3%] Building CXX object modules/rgbd/CMakeFiles/opencv_rgbd_pch_dephelp.dir/opencv_rgbd_pch_dephelp.cxx.o
[  3%] Building CXX object modules/saliency/CMakeFiles/opencv_saliency_pch_dephelp.dir/opencv_saliency_pch_dephelp.cxx.o
[  3%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio_pch_dephelp.dir/opencv_videoio_pch_dephelp.cxx.o
[  3%] Building CXX object modules/photo/CMakeFiles/opencv_photo_pch_dephelp.dir/opencv_photo_pch_dephelp.cxx.o
[  3%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d_pch_dephelp.dir/opencv_features2d_pch_dephelp.cxx.o
[  3%] Building CXX object modules/flann/CMakeFiles/opencv_flann_pch_dephelp.dir/opencv_flann_pch_dephelp.cxx.o
[  3%] Building CXX object modules/structured_light/CMakeFiles/opencv_structured_light_pch_dephelp.dir/opencv_structured_light_pch_dephelp.cxx.o
[  3%] Built target opencv_reg_pch_dephelp
[  4%] Building CXX object modules/stereo/CMakeFiles/opencv_stereo_pch_dephelp.dir/opencv_stereo_pch_dephelp.cxx.o
[  4%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image.c.o
[  4%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Half/half.cpp.o
[  4%] Building CXX object modules/line_descriptor/CMakeFiles/opencv_line_descriptor_pch_dephelp.dir/opencv_line_descriptor_pch_dephelp.cxx.o
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_color_convert_all.c.o
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_color_convert_rgbs.c.o
[  5%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/arena.cc.o
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_bilateral.c.o
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_box.c.o
[  5%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Iex/IexBaseExc.cpp.o
In file included from /home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Half/half.cpp:48:0:
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Half/half.h: In constructor 'half::half(float)':
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Half/half.h:471:18: warning: ISO C++1z does not allow 'register' storage class specifier [-Wregister]
     register int e = (x.i >> 23) & 0x000001ff;
                  ^
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Half/half.h:482:22: warning: ISO C++1z does not allow 'register' storage class specifier [-Wregister]
         register int m = x.i & 0x007fffff;
                      ^
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_canny.c.o
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_gaussian.c.o
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_general.c.o
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Half/half.cpp: In static member function 'static short int half::convert(int)':
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Half/half.cpp:98:18: warning: ISO C++1z does not allow 'register' storage class specifier [-Wregister]
     register int s =  (i >> 16) & 0x00008000;
                  ^
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Half/half.cpp:99:18: warning: ISO C++1z does not allow 'register' storage class specifier [-Wregister]
     register int e = ((i >> 23) & 0x000000ff) - (127 - 15);
                  ^
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Half/half.cpp:100:18: warning: ISO C++1z does not allow 'register' storage class specifier [-Wregister]
     register int m =   i        & 0x007fffff;
                  ^
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_laplacian.c.o
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_morphology.c.o
[  5%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/arenastring.cc.o
[  5%] Linking C static library ../lib/libittnotify.a
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_scharr.c.o
[  5%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Iex/IexThrowErrnoExc.cpp.o
[  5%] Built target ittnotify
Scanning dependencies of target opencv_tracking_pch_dephelp
[  5%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking_pch_dephelp.dir/opencv_tracking_pch_dephelp.cxx.o
[  5%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfAcesFile.cpp.o
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_sobel.c.o
[  5%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_copy.c.o
[  5%] Linking CXX static library ../../lib/libopencv_hfs_pch_dephelp.a
[  5%] Linking CXX static library ../../lib/libopencv_dpm_pch_dephelp.a
[  5%] Linking CXX static library ../../lib/libopencv_hdf_pch_dephelp.a
[  5%] Linking CXX static library ../../lib/libopencv_plot_pch_dephelp.a
[  5%] Built target opencv_hfs_pch_dephelp
Scanning dependencies of target opencv_videostab_pch_dephelp
[  5%] Built target opencv_hdf_pch_dephelp
[  5%] Built target opencv_dpm_pch_dephelp
Scanning dependencies of target opencv_xfeatures2d_pch_dephelp
Scanning dependencies of target opencv_ximgproc_pch_dephelp
[  5%] Built target opencv_plot_pch_dephelp
[  5%] Linking CXX static library ../../lib/libopencv_img_hash_pch_dephelp.a
[  5%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/extension_set.cc.o
[  5%] Built target opencv_img_hash_pch_dephelp
[  5%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfAttribute.cpp.o
[  5%] Linking CXX static library ../../lib/libopencv_text_pch_dephelp.a
[  5%] Linking CXX static library ../../lib/libopencv_freetype_pch_dephelp.a
[  5%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab_pch_dephelp.dir/opencv_videostab_pch_dephelp.cxx.o
[  5%] Linking CXX static library ../../lib/libopencv_ccalib_pch_dephelp.a
[  5%] Built target opencv_freetype_pch_dephelp
[  5%] Built target opencv_text_pch_dephelp
[  6%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_copy_channel.c.o
[  6%] Building CXX object modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d_pch_dephelp.dir/opencv_xfeatures2d_pch_dephelp.cxx.o
Scanning dependencies of target opencv_aruco_pch_dephelp
[  6%] Building CXX object modules/ximgproc/CMakeFiles/opencv_ximgproc_pch_dephelp.dir/opencv_ximgproc_pch_dephelp.cxx.o
[  6%] Built target opencv_ccalib_pch_dephelp
Scanning dependencies of target opencv_bgsegm_pch_dephelp
[  6%] Building CXX object modules/aruco/CMakeFiles/opencv_aruco_pch_dephelp.dir/opencv_aruco_pch_dephelp.cxx.o
Scanning dependencies of target opencv_face_pch_dephelp
[  6%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_copy_make_border.c.o
[  6%] Building CXX object modules/bgsegm/CMakeFiles/opencv_bgsegm_pch_dephelp.dir/opencv_bgsegm_pch_dephelp.cxx.o
[  6%] Linking CXX static library ../../lib/libopencv_xobjdetect_pch_dephelp.a
[  6%] Building CXX object modules/face/CMakeFiles/opencv_face_pch_dephelp.dir/opencv_face_pch_dephelp.cxx.o
[  6%] Linking CXX static library ../../lib/libopencv_dnn_objdetect_pch_dephelp.a
[  6%] Built target opencv_xobjdetect_pch_dephelp
[  6%] Built target opencv_dnn_objdetect_pch_dephelp
[  6%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_copy_merge.c.o
Scanning dependencies of target opencv_optflow_pch_dephelp
Scanning dependencies of target opencv_stitching_pch_dephelp
[  6%] Linking CXX static library ../../lib/libopencv_dnn_pch_dephelp.a
[  6%] Built target opencv_dnn_pch_dephelp
Scanning dependencies of target gen_opencv_python_source
[  6%] Generate files for Python bindings and documentation
[  7%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow_pch_dephelp.dir/opencv_optflow_pch_dephelp.cxx.o
[  7%] Building CXX object modules/stitching/CMakeFiles/opencv_stitching_pch_dephelp.dir/opencv_stitching_pch_dephelp.cxx.o
[  7%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/generated_message_table_driven_lite.cc.o
In file included from /home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/IlmImf/ImfHeader.h:51:0,
                 from /home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/IlmImf/ImfAcesFile.h:80,
                 from /home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/IlmImf/ImfAcesFile.cpp:41:
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:227:34: error: ISO C++1z does not allow dynamic exception specifications
     const Vec2 & normalizeExc () throw (Iex::MathExc);
                                  ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:231:37: error: ISO C++1z does not allow dynamic exception specifications
     Vec2<T>  normalizedExc () const throw (Iex::MathExc);
                                     ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:439:34: error: ISO C++1z does not allow dynamic exception specifications
     const Vec3 & normalizeExc () throw (Iex::MathExc);
                                  ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:443:37: error: ISO C++1z does not allow dynamic exception specifications
     Vec3<T>  normalizedExc () const throw (Iex::MathExc);
                                     ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:621:37: error: ISO C++1z does not allow dynamic exception specifications
     const Vec4 &    normalizeExc () throw (Iex::MathExc);
                                     ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:625:44: error: ISO C++1z does not allow dynamic exception specifications
     Vec4<T>         normalizedExc () const throw (Iex::MathExc);
                                            ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:713:30: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<short>::normalizeExc () throw (Iex::MathExc);
                              ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:722:37: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<short>::normalizedExc () const throw (Iex::MathExc);
                                     ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:737:28: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<int>::normalizeExc () throw (Iex::MathExc);
                            ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:746:35: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<int>::normalizedExc () const throw (Iex::MathExc);
                                   ^~~~~
[  7%] Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_copy_split.c.o
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:761:30: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<short>::normalizeExc () throw (Iex::MathExc);
                              ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:770:37: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<short>::normalizedExc () const throw (Iex::MathExc);
                                     ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:785:28: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<int>::normalizeExc () throw (Iex::MathExc);
                            ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:794:35: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<int>::normalizedExc () const throw (Iex::MathExc);
                                   ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:808:30: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<short>::normalizeExc () throw (Iex::MathExc);
                              ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:817:37: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<short>::normalizedExc () const throw (Iex::MathExc);
                                     ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:832:28: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<int>::normalizeExc () throw (Iex::MathExc);
                            ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:841:35: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<int>::normalizedExc () const throw (Iex::MathExc);
                                   ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:1211:26: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<T>::normalizeExc () throw (Iex::MathExc)
                          ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:1248:33: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<T>::normalizedExc () const throw (Iex::MathExc)
                                 ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:1703:26: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<T>::normalizeExc () throw (Iex::MathExc)
                          ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:1742:33: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<T>::normalizedExc () const throw (Iex::MathExc)
                                 ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:2108:26: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<T>::normalizeExc () throw (Iex::MathExc)
                          ^~~~~
/home/irodriguez/anaconda3/conda-bld/opencv_1533305047834/work/3rdparty/openexr/Imath/ImathVec.h:2149:33: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<T>::normalizedExc () const throw (Iex::MathExc)

**Comment by hajapy** [comment]
It sounds like you are trying to use this recipe to build your own package (presumably to change some of the build parameters?). That is unfortunately not an issue with this feedstock or the package built by it. If you want to simply use the package without changes just install it into your conda env using the conda-forge channel.

**Comment by piperod** [comment]
Thank you for your reply. Do you know if there is a plan for generate this package to have cuda support?
