### ISSUE TITLE
Python 3.7 build

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/opencv-feedstock#121]
Hello, currently no packages are built for Python 3.7. What needs to be done to do so?

**Comment by hmaarrfk** [comment]
I thing feedstocks will be updated magically by a bot when their dependencies are met.

**Comment by hoechenberger** [comment]
Thanks, an updated build is now available.

**Comment by hmaarrfk** [comment]
For python 3.7? On what channel?

**Comment by hoechenberger** [comment]
@hmaarrfk Sorry, my bad. I accidentally installed a mixture of `defaults` and `conda-forge` packages. `opencv` was installed from `defaults`. So this issue is not resolved. Is there anything I / we can do to speed up the process?

**Comment by hmaarrfk** [comment]
https://conda-forge.org/status/

**Comment by hmaarrfk** [comment]
It seems that qt isn't built yet, and opencv depends on qt. So it might be for a few more days / weeks.

The python upgrade coincided with a compiler upgrade, so many C-packages just had to be rebuilt from scratch.
