### ISSUE TITLE
python-opencv without qt

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/opencv-feedstock#122]
Man this is a hard one, but the current python-opencv depends on qt, which is fine, except I want to install PySide2 and the one from conda-forge is a little old.

Unfortunately, the opencv python library is a monolithic file `cv2.cpython-36m-x86_64-linux-gnu.so` so I don't know of a good way to split it up. It would probably require two seperate packages, which is going to duplicate packaging efforts.

Anyway, I just wanted to put it out there,

**Comment by hmaarrfk** [comment]
Would you accept a PR that created a variant without QT?

MacOSX already compiles opencv without QT so I don't think it would be a stretch to think to think that we can offer this on windows/linux

**Comment by jakirkham** [comment]
Sounds like it would be better to spend effort upgrading PySide2 instead. WDYT?

**Comment by hmaarrfk** [comment]
I've been trying to compile QT. Really hard.....
We can try to get Qt 5.9 from Anaconda's recipes. 5.9 is LTS too...

PySide2 5.6 might be really hard to update.
5.9 might be more realistic, but really 5.11 is the only officially supported version of PySide2.

There are probably a few reasons why we might want to try and have opencv variants:

1. Different versions of QT: 5.9, 5.6 and without
2. With/without python? Seemed to have been a requested, though that seems to be more appropriate for a split package which just picks out the python module.

**Comment by hmaarrfk** [comment]
Finally opencv for python needs some upstream love. The library is a monolithic beast. So it Is too hard to split up. 

I would personally use cases for using python and open cv without the qt libraries for things like Jupiter and bokeh.

**Comment by hmaarrfk** [comment]
The status of the qt build process has gotten much better since the synchronization with defaults. I'm going to close this as an issue unless other people want it.
