### ISSUE TITLE
OpenCV looking for png.h in wrong location

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/opencv-feedstock#127]
Appears to want to find `png.h` in `${PREFIX}/include/libpng/png.h`, but it is in `${PREFIX}/include/libpng16/png.h` instead. We either should symlink this directory in `libpng` or add a hack to OpenCV to do this.

```
-- Looking for /Users/travis/miniconda3/conda-bld/opencv_1536446791779/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/libpng/png.h
-- Looking for /Users/travis/miniconda3/conda-bld/opencv_1536446791779/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/libpng/png.h - not found
```

ref: https://travis-ci.org/conda-forge/opencv-feedstock/jobs/426208605#L784

**Comment by hmaarrfk** [comment]
I patched this in my own version.

4.0 patch link: https://github.com/ramonaoptics/opencv-feedstock/blob/mine/recipe/include_libpng16.patch

Do you think this is appropriiate? should we open an issue upstream?

**Comment by hmaarrfk** [comment]
Is this a bug in the conda-forge version of libpng?

opencv master still include `include/libpng`: https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/grfmt_png.cpp#L62

Ubuntu symlinks a bunch of stuff:
```
➤ ls /usr/include/ -lah | grep png 
lrwxrwxrwx  1 root root    8 Jul 10 14:37 libpng -> libpng16
drwxr-xr-x  2 root root 4.0K Dec 17 14:11 libpng16
lrwxrwxrwx  1 root root   18 Jul 10 14:37 pngconf.h -> libpng16/pngconf.h
lrwxrwxrwx  1 root root   14 Jul 10 14:37 png.h -> libpng16/png.h
lrwxrwxrwx  1 root root   21 Jul 10 14:37 pnglibconf.h -> libpng16/pnglibconf.h
```

**Comment by hmaarrfk** [comment]
I guess this isn't an issue anymore???

**Comment by jakirkham** [comment]
I think it came up in the conda-forge build. So if we aren’t seeing it any more, it can be closed out. 🙂

**Comment by hmaarrfk** [comment]
This is what we get now

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=81529&view=logs&jobId=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&taskId=0a2070c1-8027-59fc-ddea-6aec050600c1&lineStart=462&lineEnd=463&colStart=1&colEnd=1

```
-- Found PNG: $PREFIX/lib/libpng.dylib (found version "1.4.12") 
-- Looking for /Library/Frameworks/Mono.framework/Headers/libpng/png.h
-- Looking for /Library/Frameworks/Mono.framework/Headers/libpng/png.h - not found
```

**Comment by hmaarrfk** [comment]
xref: https://github.com/opencv/opencv/issues/16321
