### ISSUE TITLE
ffmpeg w/ssl

### ISSUE THREAD

**Issue by peregilk** [conda-forge/opencv-feedstock#135]
Im having some issues with opencv-ffmpeg when opening links over ssl. Seems like the conda-forge version of opencv has the ffmpeg backend. However, the ffmpeg does not seem to have ssl enabled. Is this correct?

**Comment by hmaarrfk** [comment]
I'm assuming you are on linux.

You are right, it seems that ffmpeg isn't built with openssl support

https://github.com/conda-forge/ffmpeg-feedstock/blob/master/recipe/meta.yaml
https://github.com/conda-forge/ffmpeg-feedstock/blob/master/recipe/build.sh#L9

Maybe you can make a PR to update the ffmpeg recipe?

**Comment by peregilk** [comment]
Thanks. I will.

**Comment by hmaarrfk** [comment]
I guess the discussion https://github.com/conda-forge/ffmpeg-feedstock/issues/68

closed off the issue.
