### ISSUE TITLE
3.4 vs 4.0

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/opencv-feedstock#137]
OpenCV 4.0 has been released removing much of the C-api
https://opencv.org/opencv-4-0-0.html

I'm inclined not to care, but should we create a branch point for Opencv 3.4 in case any new security updates come to that branch?

**Comment by jakirkham** [comment]
We can always create a branch based off of the last 3.4 release for continued maintenance after the fact. This can be any time we need really.

It likely still matters for C++ libraries making use of OpenCV. Some of which are in conda-forge. So we may need to maintain it to provide builds with updated dependencies. The same happened with OpenCV 2 for a while.

**Comment by hmaarrfk** [comment]
it seems nobody has complained recently about 3.4 support. I think there has been some significant work to harden the build process for 4.0.

The remaining challenge is that we have diverged more from AD.
