### ISSUE TITLE
segfault on linux due to openmp???

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/opencv-feedstock#139]
I'm using opencv and dask, both installed from conda-forge on python 3.6 on linux. On windows, things seem to be OK. not sure about macosx

on 3.4.3, I didn't notice any issues. now in 3.4.4 on linux (ubuntu 18.04), I am starting to get this error:
```
conda create --name foobar conda-forge::opencv=3.4.4 conda-forge::dask --yes
conda activate foobar
```

```python
import numpy as np
from dask import delayed, compute
import cv2

def bayer2rgb(arr):
    return cv2.cvtColor(arr, cv2.COLOR_BAYER_GR2RGB)

data = np.zeros((400, 400), dtype=np.uint8)

images = delayed(bayer2rgb)(data)

compute(images, scheduler='single-threaded')
print('this will segfault trying to allocate 900GB of memory')
compute(images, scheduler='threads')
```
```
this will segfault trying to allocate 900GB of memory

libgomp: Out of memory allocating 927712937064 bytes
```

now, this issue only arises with 3.4.4 (and 4.0.0 from my channel built using conda-smithy tools). In fact, if I install `opencv-python` from pip, it seems fine.

Any thoughts as to why this might be happening here????

Maybe @mrocklin or @jakirkham can help me get an MCVE that doesn't include dask :/

**Comment by mrocklin** [comment]
it looks like this doesn't use any parallelism, instead it just runs things
in a separate thread.  I would use the concurrent.futures module for this

e = concurrent.futures.ThreadPoolExecutor()
future = e.submit(bayer2rgb, data)
future.result()

**Comment by hmaarrfk** [comment]
Thanks @mrocklin !! Yes the example I showed doesn't use any parralelism on the dask side. Not too sure what happens in opencv. Apparently this kind of error happens due to some uninitialized variable, I just wanted to remove dask from the equation in case it came up.

I think with this example I'll open up an issue on the official opencv github and see what they have to say about it.

putting it all together, it still creates a segfault:

```python
import numpy as np
import cv2
from concurrent.futures import ThreadPoolExecutor
def bayer2rgb(arr):
    return cv2.cvtColor(arr, cv2.COLOR_BAYER_GR2RGB)

data = np.zeros((400, 400), dtype=np.uint8)

e = ThreadPoolExecutor()
future = e.submit(bayer2rgb, data) 
future.result()
```

**Comment by hmaarrfk** [comment]
I don't know why I didn't find it on opencv before. but here is the issue:

https://github.com/opencv/opencv/issues/13207

I'll add the patch and rebuild for conda-forge
