### ISSUE TITLE
OpenCV (OSX) broken by new jasper

### ISSUE THREAD

**Issue by pgunn** [conda-forge/opencv-feedstock#147]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/pgunn/anaconda3/envs/opencv_test1:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12           h9d4d9ac_1005    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
ffmpeg                    4.1               heb45b42_1001    conda-forge
fontconfig                2.13.1            h1e4e890_1000    conda-forge
freetype                  2.9.1             h597ad8a_1005    conda-forge
gettext                   0.19.8.1          hcca000d_1001    conda-forge
giflib                    5.1.4             h1de35cc_1001    conda-forge
glib                      2.56.2            h67dad55_1001    conda-forge
gmp                       6.1.2             h0a44026_1000    conda-forge
gnutls                    3.6.5             h53004b3_1001    conda-forge
graphite2                 1.3.13            h2098e52_1000    conda-forge
harfbuzz                  1.9.0             h9889186_1001    conda-forge
hdf5                      1.10.4          nompi_h5598ddc_1105    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
jasper                    1.900.31             h636a363_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
libcxx                    7.0.0                h2d50403_2    conda-forge
libffi                    3.2.1             h0a44026_1005    conda-forge
libgfortran               3.0.0                      1001    conda-forge
libiconv                  1.15              h1de35cc_1004    conda-forge
libpng                    1.6.36            ha441bb4_1000    conda-forge
libtiff                   4.0.10            h344961e_1002    conda-forge
libwebp                   1.0.2                h801f6e5_1    conda-forge
libxml2                   2.9.8             hf14e9c8_1005    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
nettle                    3.4.1             h1de35cc_1002    conda-forge
numpy                     1.15.4          py36_blas_openblashb06ca3d_0  [blas_openblas]  conda-forge
openblas                  0.3.3                ha44fe06_1    conda-forge
opencv                    3.4.4           py36_blas_openblash27d9bbe_1203  [blas_openblas]  conda-forge
openh264                  1.8.0             hd9629dc_1000    conda-forge
openssl                   1.0.2p            h1de35cc_1002    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pip                       19.0.2                   py36_0    conda-forge
pixman                    0.34.0            h1de35cc_1003    conda-forge
python                    3.6.7             h4a56312_1001    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
setuptools                40.8.0                   py36_0    conda-forge
sqlite                    3.26.0            h1765d9f_1000    conda-forge
tk                        8.6.9             ha441bb4_1000    conda-forge
wheel                     0.33.0                   py36_0    conda-forge
x264                      1!152.20180717    h1de35cc_1001    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.3.3                         1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : opencv_test1
    active env location : /Users/pgunn/anaconda3/envs/opencv_test1
            shell level : 1
       user config file : /Users/pgunn/.condarc
 populated config files : /Users/pgunn/.condarc
          conda version : 4.6.3
    conda-build version : 3.0.27
         python version : 3.6.6.final.0
       base environment : /Users/pgunn/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/pgunn/anaconda3/pkgs
                          /Users/pgunn/.conda/pkgs
       envs directories : /Users/pgunn/anaconda3/envs
                          /Users/pgunn/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.3 requests/2.19.1 CPython/3.6.6 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 1189:1189
             netrc file : None
           offline mode : False
```
</details>

With the new version of Jasper uploaded yesterday (1.900.31):

```
C02VF0SQHTDH:~$ python
Python 3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/pgunn/anaconda3/envs/opencv_test1/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libjasper.1.dylib
  Referenced from: /Users/pgunn/anaconda3/envs/opencv_test1/lib/libopencv_imgcodecs.3.4.dylib
  Reason: image not found
```

After downgrading to Jasper 1.900.1, the import works. I spoke with @mariusvniekerk on Gitter and he suggested a rebuild of OpenCV would fix the issue.

**Comment by pgunn** [comment]
They've pulled the new package until they can fix opencv. Will need to verify this tomorrow, and after that will revert the docs change.

**Comment by jakirkham** [comment]
We are rebuilding it now. Though am now seeing `jasper` was pulled. So we may need to rebuild again when it gets added back.

**Comment by hmaarrfk** [comment]
maybe see what happens with https://github.com/conda-forge/opencv-feedstock/pull/149

**Comment by hmaarrfk** [comment]
re people still running into this issue? We've rebuilt opencv quite a few times since it was originally open.

**Comment by hmaarrfk** [comment]
it seem that this is no longer an issue. Please reopen if it still is for you.

**Comment by swagner-astro** [comment]
Hi, not sure if this is the right place to put it but I am having the same problems. The installation underneath worked fine but when I try to use it I get the error:
ImportError: dlopen(/Users/Sarah/miniconda3/lib/python3.8/site-packages/cv2.cpython-38-darwin.so, 2): Library not loaded: @rpath/libjpeg.9.dylib
Referenced from: /Users/Sarah/miniconda3/lib/libopencv_imgcodecs.4.4.0.dylib
Reason: Incompatible library version: libopencv_imgcodecs.4.4.dylib requires version 14.0.0 or later, but libjpeg.9.dylib provides version 12.0.0

INSTALLATION:
The following NEW packages will be INSTALLED:

bzip2 pkgs/main/osx-64::bzip2-1.0.8-h1de35cc_0
cairo pkgs/main/osx-64::cairo-1.16.0-h8023c5d_1
ffmpeg conda-forge/osx-64::ffmpeg-4.3-hd0c0d6a_0
fontconfig pkgs/main/osx-64::fontconfig-2.13.1-ha9ee91d_0
gettext pkgs/main/osx-64::gettext-0.21.0-h7535e17_0
glib pkgs/main/osx-64::glib-2.68.2-hdf23fa2_0
gmp pkgs/main/osx-64::gmp-6.2.1-h23ab428_2
gnutls pkgs/main/osx-64::gnutls-3.6.15-hed9c0bf_0
graphite2 pkgs/main/osx-64::graphite2-1.3.14-h38d11af_0
harfbuzz pkgs/main/osx-64::harfbuzz-2.8.1-ha8c618c_0
hdf5 pkgs/main/osx-64::hdf5-1.10.6-hdbbcd12_0
icu pkgs/main/osx-64::icu-58.2-h0a44026_3
jasper pkgs/main/osx-64::jasper-1.900.1-h1f36771_4
lame pkgs/main/osx-64::lame-3.100-h1de35cc_0
libblas conda-forge/osx-64::libblas-3.8.0-14_mkl
libcblas conda-forge/osx-64::libcblas-3.8.0-14_mkl
libiconv pkgs/main/osx-64::libiconv-1.16-h1de35cc_0
libidn2 pkgs/main/osx-64::libidn2-2.3.1-h9ed2024_0
liblapack conda-forge/osx-64::liblapack-3.8.0-14_mkl
liblapacke conda-forge/osx-64::liblapacke-3.8.0-14_mkl
libopencv conda-forge/osx-64::libopencv-4.4.0-py38_2
libtasn1 pkgs/main/osx-64::libtasn1-4.16.0-h9ed2024_0
libunistring pkgs/main/osx-64::libunistring-0.9.10-h9ed2024_0
libwebp-base pkgs/main/osx-64::libwebp-base-1.2.0-h9ed2024_0
libxml2 pkgs/main/osx-64::libxml2-2.9.12-hcdb78fc_0
llvm-openmp pkgs/main/osx-64::llvm-openmp-10.0.0-h28b9765_0
nettle pkgs/main/osx-64::nettle-3.7.3-h230ac6f_1
opencv conda-forge/osx-64::opencv-4.4.0-py38_2
openh264 conda-forge/osx-64::openh264-2.1.1-hd174df1_0
pcre pkgs/main/osx-64::pcre-8.45-h23ab428_0
pixman pkgs/main/osx-64::pixman-0.40.0-haf1e3a3_0
py-opencv conda-forge/osx-64::py-opencv-4.4.0-py38h23f93f0_2
x264 pkgs/main/osx-64::x264-1!152.20180806-h1de35cc_0

The following packages will be UPDATED:

ca-certificates 2021.1.19-hecd8cb5_1 --> 2021.5.25-hecd8cb5_1
certifi 2020.12.5-py38hecd8cb5_0 --> 2021.5.30-py38hecd8cb5_0
conda 4.9.2-py38hecd8cb5_0 --> 4.10.3-py38hecd8cb5_0
jpeg pkgs/main::jpeg-9b-he5867d9_2 --> conda-forge::jpeg-9d-hbcb3906_0

**Comment by hmaarrfk** [comment]
can you please open a new issue. conda forge moves quite quickly and an issue from 2 years ago is likely stale. 

Please also see the syntax highlighting section. You can just set the language to `bash` if that helps But the monospaced font really helps read code.

**Comment by swagner-astro** [comment]
@pgunn  was so kind to do that here: 
https://github.com/flatironinstitute/CaImAn/issues/892 

I think I have used the wrong installation command and that is why it wasn't working. 
All good now, thanks!
