### ISSUE TITLE
Backports to 3.4

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/opencv-feedstock#177]
Just a meta issue to keep track of things.

- [x] New openblas https://github.com/conda-forge/opencv-feedstock/pull/152/files
- [x] V4L https://github.com/conda-forge/opencv-feedstock/pull/161
- [ ] Configuration https://github.com/conda-forge/opencv-feedstock/pull/163
- [x] HDF5 https://github.com/conda-forge/opencv-feedstock/pull/164
- [x] Windows CMake https://github.com/conda-forge/opencv-feedstock/pull/171

**Comment by hajapy** [comment]
Hey, not sure why you felt this was ready to close, I still see a number of important differences (such as the use of liblapacke), config verification, and cmake arguments used in the build scripts: https://github.com/conda-forge/opencv-feedstock/compare/3.4.x..master

**Comment by hmaarrfk** [comment]
I really thought I had included all of those. In one of my versions I had simply pulled in the recipe from master. I'll double check.

**Comment by hmaarrfk** [comment]
In addition to those listed above, we will have to backports qt 5.12 once all passes on master. Seems to be a pinning issue maybe

**Comment by hmaarrfk** [comment]
Finally

**Comment by hajapy** [comment]
Thanks for the hard work!

**Comment by hmaarrfk** [comment]
no, i didn't bump the build number.... for qt 5.12
