### ISSUE TITLE
pip install opencv-python not detecting opencv installed by conda

### ISSUE THREAD

**Issue by farleylai** [conda-forge/opencv-feedstock#188]
By installing `opencv` through `conda`, `cv2` is already provided in Python to import.
However, some `pip` package such as `mmdetection` that requires `opencv-python` due to a transitive dependency on `imagecorruptions` would have `pip` not detecting `opencv` installed by `conda` such that `opencv-python` is installed side by side with `opencv` as follows:

```
opencv                    4.1.1            py37ha799480_1    conda-forge
opencv-python             4.1.1.26                 pypi_0    pypi
```

The difference seems like pypi `opencv-python` uses its own ffmpeg while conda `opencv` depends on conda `ffmpeg` package. Nonetheless, this is not only confusing but also involves duplicate dependency on the popular `ffmpeg` package. Is it really necessary or just a temporary workaround for some reason?

**Comment by hajapy** [comment]
Generally speaking, mixing pip packages and conda packages remains experimental and to be avoided where possible. In this case my recommendation would be to get mmdetection into conda-forge. Also, worth noting is that the opencv pip packages are unofficial and also come in various flavors (opencv-python-headless for example), so a general solution can’t just target a single package name for mutual exclusivity.

**Comment by farleylai** [comment]
Maybe `opencv-python` was created for the standalone purpose in case of dependency on pre-installed `ffmpeg` libraries. If it's a conda package, the dependency has to satisfy the most constrained one. For example (assume it is the case), a package that requires `pyAV` and `cv2`. However, `pyAV` is not updated often and depends on `ffmpeg=4.0.0` that is not built with SSL enabled. On the other hand, `cv2` must depend on `ffmpeg>=4.1.1` with SSL support to open https url. In this case, installing `opencv-python` side by side might be the workaround to avoid the dependency conflict. 

Therefore, does conda package build support static and dynamic(shared) variants at the same time to address potential dependency conflicts like this?

**Comment by hmaarrfk** [comment]
No, but I've been toying with the idea of knocking out dependencies with a larger build matrix. If you make the PR for a build no ffmpeg, I can review it.

**Comment by hmaarrfk** [comment]
If this is a dealbreaker for you, I would suggest building pyav yourself locally and uploading to your own channel while Some of the cross linked posts go through

You can see the recepe I updated in https://github.com/conda-forge/av-feedstock/pull/19

**Comment by hmaarrfk** [comment]
I'm not really trying to push the burden onto you, but it might very well be that we need a newer version of ffmpeg for opencv.

It is much easier to rebuild pyav than opencv ;)

Anyway, if this build passes, I'll ask others if it is a good idea to unpin (typically it is)
https://github.com/conda-forge/opencv-feedstock/pull/190

**Comment by farleylai** [comment]
I would like to contribute but am not that familiar with your workflow.

1. Since pyAV mentions conda installation. Their conda distribution is official in that sense? Then how are the version dependency set (manually or automatically from pyAV repo)? I only saw the version sepcified in `v-feedstock/.ci_support/linux_c_compilergccpython3.7.yaml`
2. Their document [HACKING](https://github.com/mikeboers/PyAV/blob/develop/HACKING.rst) mentions the version compatibility which might be the concern for not release build with ffmpeg 4.1+? Should ask for their elaboration beforehand?

> Differences are handled at compile time, in C, by checking against LIBAV*_VERSION_INT macros. We have not been able to perform this sort of checking in Cython as we have not been able to have it fully remove the code-paths, and so there are missing functions in newer FFmpeg's, and deprecated ones that emit compiler warnings in older FFmpeg's.

**Comment by hmaarrfk** [comment]
hmmm, the incompatibilities might be an issue.

You can try to help debug this: 
https://github.com/conda-forge/opencv-feedstock/pull/190

If you can build the recepie locally, you can upload it to your own channel channel immediately while things get debugged.

**Comment by farleylai** [comment]
To make it clear, there are actually two folds of the issue:

1. pip packages that needs OpenCV tend to require `opencv-python` which is straightforward but NOT official
2. Even a package provides its official conda distribution, the dependency on `ffmpeg` can be out of dated, causing conflicts with `opencv`

For (1), is this `opencv` by conda-forge can be viewed as official? If that is the case, it would be a good reason to talk those pip package developers into distribution in conda packages. 
For (2), it has to be verified by the package developers I assume.

**Comment by hmaarrfk** [comment]
1. conda-forge is as official as any open source distribution. People **other** than the original developer repackage the package.
2. We verify things with sha256 hashes.

To support multiple versions of ffmpeg is tricky. I am tempted to say that conda-forge shouldn't support old software build matricies unless there is a very good reason.

Are you targetting windows, mac, or linux? Depending on what you are targetting, you might be better off to build the package you need yourself using conda-smithy and the conda-forge recepies modified to your liking.

Linux is really easy to build locally. Windows a little harder. Mac, I'm not sure.

**Comment by farleylai** [comment]
Thanks for the advice.
My use case is mainly for Ubuntu/Linux.
Testing on other OS is so far unlikely in my environment.
I will look into `conda-smithy` sooner or later.

**Comment by hmaarrfk** [comment]
In that case,

You can clone the repos you need locally,
make the modification you need,
 then rerender with
```
conda smithy rerender
```
and build with
```
python build_locally.py
```

you might need docker too.

Then you can upload the packages you need to your own channel.

While conda-forge is great to get things working long term. short term, it is often a bad solution when you get stuck on dependencies like this, where your requirements might be contrary to the larger vision of the project.

**Comment by hmaarrfk** [comment]
https://conda-forge.org/docs/maintainer/updating_pkgs.html#testing-changes-locally

**Comment by farleylai** [comment]
What is the right way to specify ffmpeg-4.1?

I first modified `meta.yaml` to specify `ffmpeg 4.1` in both host and run sections but the generated `.ci_support/linux_python3.7.yaml` will not include ffmpeg and its version.
So should I just modify `.ci_support/linux_python3.7.yaml` directly for the build?
This actually works without errors throughout the build:

```sh
## Package Plan ##

  environment location: /home/conda/feedstock_root/build_artifacts/av_1571023066162/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla


The following NEW packages will be INSTALLED:

    _libgcc_mutex:   0.1-main                  defaults   
    av:              6.2.0-py37h866369f_0      local      
    bzip2:           1.0.8-h516909a_1          conda-forge
    ca-certificates: 2019.9.11-hecc5488_0      conda-forge
    ffmpeg:          4.1.3-h167e202_0          conda-forge
    freetype:        2.10.0-he983fc9_1         conda-forge
    gmp:             6.1.2-hf484d3e_1000       conda-forge
    gnutls:          3.6.5-hd3a4fd2_1002       conda-forge
    jpeg:            9c-h14c3975_1001          conda-forge
    lame:            3.100-h14c3975_1001       conda-forge
    libblas:         3.8.0-13_openblas         conda-forge
    libcblas:        3.8.0-13_openblas         conda-forge
    libffi:          3.2.1-he1b5a44_1006       conda-forge
    libgcc-ng:       9.1.0-hdf63c60_0          defaults   
    libgfortran-ng:  7.3.0-hdf63c60_2          conda-forge
    libiconv:        1.15-h516909a_1005        conda-forge
    liblapack:       3.8.0-13_openblas         conda-forge
    libopenblas:     0.3.7-h6e990d7_1          conda-forge
    libpng:          1.6.37-hed695b0_0         conda-forge
    libstdcxx-ng:    9.1.0-hdf63c60_0          defaults   
    libtiff:         4.0.10-h57b8799_1003      conda-forge
    lz4-c:           1.8.3-he1b5a44_1001       conda-forge
    ncurses:         6.1-hf484d3e_1002         conda-forge
    nettle:          3.4.1-h1bed415_1002       conda-forge
    numpy:           1.17.2-py37h95a1406_0     conda-forge
    olefile:         0.46-py_0                 conda-forge
    openh264:        1.8.0-hdbcaa40_1000       conda-forge
    openssl:         1.1.1c-h516909a_0         conda-forge
    pillow:          6.2.0-py37h6b7be26_0      conda-forge
    python:          3.7.3-h33d41f4_1          conda-forge
    readline:        8.0-hf8c457e_0            conda-forge
    sqlite:          3.30.1-hcee41ef_0         conda-forge
    tk:              8.6.9-hed695b0_1003       conda-forge
    x264:            1!152.20180806-h14c3975_0 conda-forge
    xz:              5.2.4-h14c3975_1001       conda-forge
    zlib:            1.2.11-h516909a_1006      conda-forge
    zstd:            1.4.0-h3b9ef0a_0          conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/home/conda/feedstock_root/build_artifacts/av_1571023066162/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/av_1571023066162/test_tmp
import: 'av'
import: 'av'

Resource usage statistics from testing av:
   Process count: 1
   CPU time: unavailable
   Memory: 704.0K
   Disk usage: 16B
   Time elapsed: 0:00:02.1

TEST END: /home/conda/feedstock_root/build_artifacts/linux-64/av-6.2.0-py37h866369f_0.tar.bz2
Renaming work directory,  /home/conda/feedstock_root/build_artifacts/av_1571023066162/work  to  /home/conda/feedstock_root/build_artifacts/av_1571023066162/work_moved_av-6.2.0-py37h866369f_0_linux-64_main_build_loop
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /home/conda/feedstock_root/build_artifacts/linux-64/av-6.2.0-py37h866369f_0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
####################################################################################
Resource usage summary:

Total time: 0:03:20.6
CPU usage: sys=0:00:00.6, user=0:00:22.6
Maximum memory usage observed: 262.0M
Total disk usage observed (not including envs): 13.6K
+ [[ False != \F\a\l\s\e ]]
+ touch /home/conda/feedstock_root/build_artifacts/conda-forge-build-done-linux_python3.7
+ test -f /home/ml/farleylai/local/projects/av-feedstock/build_artifacts/conda-forge-build-done-linux_python3.7
```

BTW, the build does not seem to use something like `make -jN` to utilize multi-cores. Is there's a way to specify that?

Also, the build does not seem to work with docker remapping which would be better to mention in the documentation though.

**Comment by hmaarrfk** [comment]
i would modify it in the meta.yaml file.

The .ci_support will pull in the pinnings from a centralized place if they aren't present in the meta.yaml

There isn't a good way to specify `make -jN` for python. easier to just wait.

**Comment by farleylai** [comment]
OK, I tried to specify as follows and the generated linux_python3.7.yaml does not have ffmpeg sections anymore. However, the build package plan does include ffmpeg-4.1.3.

```yaml
...
requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config  # [not win]
    - msinttypes  # [win and py27]
  host:
    - python
    - pip
    - cython
    - numpy
    - ffmpeg 4.1 
    - pillow
  run:
    - python
    - numpy
    - ffmpeg 4.1 
    - pillow
...
```

**Comment by hmaarrfk** [comment]
That should be fine. Just make sure to look at what is being pulled in during the build and test phases 

https://github.com/conda-forge/av-feedstock/pull/20

**Comment by hmaarrfk** [comment]
See if you can install av and opencv now. If you need qt as well, i've had trouble installing opencv + qt 5.12 + spyder on my computer. So i can trigger a qt 5.9 build too if needed. (then a followup qt.512 build to have a hgher build number for that one).

**Comment by hmaarrfk** [comment]
Can we close this issue now? we've since updating the ffmpeg pinnings and qt migration seems to have been completed.

**Comment by farleylai** [comment]
I think so. Things work fine at least in my use case.
