### ISSUE TITLE
Broken install on MacOS, incompatible with `hdf5` package

### ISSUE THREAD

**Issue by adam-erickson** [conda-forge/opencv-feedstock#195]
Issue:
Broken install on MacOS, incompatible with `hdf5` package.

System:
Fresh install of Anaconda3 2019.10 running on MacOS Mojave.

**Comment by hmaarrfk** [comment]
Could you please provide more information about your current environment? The details were provided in the issue template. They are important in helping us debug things.

```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>
```

**Comment by adam-erickson** [comment]
No longer installed, I've moved on to Miniconda and the error went away even though `hdf5` is still present.

**Comment by hmaarrfk** [comment]
Ok. I will close and let somebody else that can recreate request to open this again.

I have a suspicion it is due mixing conda-forge  and defaults, which can lead to these kinds of problems.
