### ISSUE TITLE
Woes with Qt 5.12

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/opencv-feedstock#199]
Issue:
I'm having random bugs with Qt 5.12.

I think I'm hitting some bugs regarding some 3D rendering

I think I'm hitting https://bugreports.qt.io/browse/QT3DS-3902

@jakirkham if I want to rebuild opencv with qt 5.9, can I increase the build number? Or would I have to make two builds, one with 5.9 and then again a new one with 5.12 with a larger build number to help the solver?

Can I say that builds in the 50s are for qt 5.12, and builds in the 0+x are for qt 5.9??

**Comment by jakirkham** [comment]
Maybe add both versions to `conda_build_config.yaml`?

**Comment by hmaarrfk** [comment]
it turned out I very likely had a memory leak. so challenging to find these.
