### ISSUE TITLE
create "fluiddyn" conda-forge package with opencv dependance

### ISSUE THREAD

**Issue by CyrilleBonamy** [conda-forge/opencv-feedstock#201]
Issue : I try to update a conda-forge package with opencv dependance. I have a lot of error messages that I did not have before.
If I remove opencv of the recipe, the package builds correctly.

Can you help me?

pull request with errors : https://github.com/conda-forge/fluiddyn-feedstock/pull/4
error messages : https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=92110

**Comment by CyrilleBonamy** [comment]
we have a lot of problems. So we will start without opencv. Sorry for the inconvenience

**Comment by hmaarrfk** [comment]
;)
