### ISSUE TITLE
4.2.0 linux py38 build off master failed

### ISSUE THREAD

**Issue by hajapy** [conda-forge/opencv-feedstock#213]
Just looking at the last build off master (4.2.0), I noticed that the linux python 3.8 build failed. Here is the log: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=110638&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=ecca2736-6363-55be-133f-faae951bb9b5&l=2061

Claims to be a config verification issue, complaining about the WITH_IPP flag. Not sure how this wouldn't have been caught in the PR nor affected the other platforms, or python versions. Maybe worth just triggering a re-build?

**Comment by hmaarrfk** [comment]
Wanna make the PR?

**Comment by hmaarrfk** [comment]
I retriggered some builds on master.

**Comment by hajapy** [comment]
That resolved it, thanks!
