### ISSUE TITLE
Installation instructions in the readme

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/opencv-feedstock#224]
This package seems to have serious incompatibilities with anaconda default.

Not too sure why, but I have a feeling it is due to some incompatibile pinnings we have with some default packages install in anaconda.

Is there a way we can add to the rerendered README.md?

**Comment by jakirkham** [comment]
Could add a `README.md` to the `recipe`. Some other feedstocks have done this as well.

**Comment by hmaarrfk** [comment]
conda-forge as a whole has become incompatible with anaconda defaults this is no longer a opencv-only challenge.
