### ISSUE TITLE
Why is ppc64le disabled?

### ISSUE THREAD

**Issue by photex** [conda-forge/opencv-feedstock#239]
Title says it all. :D I'm mainly curious if there was a particular technical problem building for powerpc or if it's more administrative.

Thanks!

**Comment by hmaarrfk** [comment]
No real reason. 

Probably because the migration hasn't gotten here and this package depends on many 3D graphics libraries

**Comment by jakirkham** [comment]
The migration can be tracked [here]( https://conda-forge.org/status/#current_migrations ) and the list of packages being migrated (along with their dependencies) can be seen [here]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/b2b30c087940055ecf8560c62e69b439488d9ffd/recipe/migrations/arch_rebuild.txt ). FWICT it looks like we are waiting for `qt`.

**Comment by Tobias-Fischer** [comment]
This issue can be closed

**Comment by hmaarrfk** [comment]
Thanks
