### ISSUE TITLE
use libjpeg-turbo?

### ISSUE THREAD

**Issue by carlodri** [conda-forge/opencv-feedstock#240]
Is there a specific reason for which OpenCV is not built with `libjpeg-turbo`? I'm almost sure there is, but just wondering if there is something we can do to move to turbo.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/conda-forge.github.io/issues/673

**Comment by hmaarrfk** [comment]
done.
