### ISSUE TITLE
adding gtk support for Linux version

### ISSUE THREAD

**Issue by zym1010** [conda-forge/opencv-feedstock#25]
I wonder if opencv can be built with GTK support, as this is needed for some opencv dependent programs, such as <https://github.com/yosinski/deep-visualization-toolbox>. Thanks.

**Comment by patricksnape** [comment]
On that I'm not sure - it depends on what the support is like for GTK across different Linux versions.

**Comment by zym1010** [comment]
@patricksnape are you saying that you want conda-forge's opencv to support those Linux versions that don't come with gtk? I can understand that. If that's the case, then maybe the solution would be compiling a custom opencv myself.

BTW, do you think GTK libraries across different Linux versions are somehow compatible? Say I compile a GTK enable opencv on CentOS 6 and run it in Ubuntu 12.04. Do you think it will work? Thanks.

**Comment by patricksnape** [comment]
Yes we want conda-forge to run on all Linux versions - we already build in a CentOS 5 docker container - which you may have already been using on your Ubuntu machine!

**Comment by zym1010** [comment]
@patricksnape  thanks!

**Comment by jakirkham** [comment]
> we already build in a CentOS 5 docker container

Sorry, correction, we use a CentOS 6 container. Details [here]( https://github.com/conda-forge/docker-images/blob/45a02c22e91631f8b133307b23eb009097250a82/linux-anvil/Dockerfile ).
