### ISSUE TITLE
Install with python 3.5 ?

### ISSUE THREAD

**Issue by hadim** [conda-forge/opencv-feedstock#26]
```
$ conda install -c conda-forge opencv
Fetching package metadata .........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - opencv
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

Any idea ?

**Comment by jakirkham** [comment]
Currently we only have OpenCV 2.x, which does not support Python 3.x. We are working on OpenCV 3.x in PR ( https://github.com/conda-forge/opencv-feedstock/pull/16 ), but have a few issues we are still trying to solve.

**Comment by hadim** [comment]
Ok so I close here and will wait for v3. Thank you.

**Comment by jakirkham** [comment]
Thanks @hadim.
