### ISSUE TITLE
Why does the bot not detect new versions

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/opencv-feedstock#263]
@conda-forge/bot  any clue as to why the bot has trouble finding new versions of opencv

**Comment by beckermr** [comment]
Can you provide a list of versions as they have been released? I suspect skipping version numbers is the issue.

**Comment by beckermr** [comment]
Ahhhhh check the version page for errors. The bot cannot parse the recipe. Multiline jinja2.

**Comment by hmaarrfk** [comment]
wow, i didn't know about that version page.

**Comment by beckermr** [comment]
yeah, we keep little gems around to make people's day at random :)

In terms of the recipe, we can remove the multiline jinja2 or we can try a PR from Isuru that might fix some of the errors related to this.

**Comment by hmaarrfk** [comment]
So the issue is the multiline jinja statement point and blank. We can work around that `+=` should do.

I can work on that this weekend, maybe.

Thanks for helping identify the issue.
