### ISSUE TITLE
Can't install both opencv 3.1.0 and matplotlib (Windows)

### ISSUE THREAD

**Issue by hadim** [conda-forge/opencv-feedstock#27]
I didn't check this bug on OS X and Linux. Only Windows.

```bash
$ conda info
Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.14+0.g4dfebe9.dirty
       python version : 3.5.2.final.0
     requests version : 2.11.0
     root environment : XXXX\Miniconda3  (writable)
  default environment : XXXX\Miniconda3
     envs directories : XXXX\Miniconda3\envs
        package cache : XXXX\Miniconda3\pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/win-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Users\brouhardlab\.condarc
         offline mode : False
    is foreign system : False
```

```bash
$ conda create -n test python --yes
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\brouhardlab\Miniconda3\envs\test:

The following NEW packages will be INSTALLED:

    certifi:        2016.8.2-py35_0 conda-forge
    pip:            8.1.2-py35_0    conda-forge
    python:         3.5.2-2         conda-forge
    setuptools:     26.1.0-py35_0   conda-forge
    vs2015_runtime: 14.0.25420-0    conda-forge
    wheel:          0.29.0-py35_0   conda-forge
    wincertstore:   0.2-py35_0      conda-forge

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# $ source activate test
#
# To deactivate this environment, use:
# $ source deactivate
#

$ source activate test
$ conda install opencv --yes
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\brouhardlab\Miniconda3\envs\test:

The following NEW packages will be INSTALLED:

    jpeg:    9b-vc14_0         conda-forge [vc14]
    libpng:  1.6.24-vc14_0     conda-forge [vc14]
    libtiff: 4.0.6-vc14_6      conda-forge [vc14]
    mkl:     11.3.3-1
    numpy:   1.11.1-py35_1
    opencv:  3.1.0-np111py35_0 conda-forge
    zlib:    1.2.8-vc14_3      conda-forge [vc14]

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
$ conda install matplotlib --yes
Fetching package metadata ...........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - matplotlib
Use "conda info <package>" to see the dependencies for each package.
```

Now it works if I uninstall `opencv` and install `matplotlib`.

```bash
$ conda remove opencv --yes
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for package removal in environment XXXXX\Miniconda3\envs\test:

The following packages will be REMOVED:

    opencv: 3.1.0-np111py35_0 conda-forge

Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
$ conda install matplotlib --yes
Fetching package metadata ...........
Solving package specifications: ..........
        1 file(s) copied.

Package plan for installation in environment XXXXX\Miniconda3\envs\test:

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.8.2-3        conda-forge
    cycler:          0.10.0-py35_0     conda-forge
    freetype:        2.6.3-vc14_1      conda-forge [vc14]
    matplotlib:      1.5.2-np111py35_5 conda-forge
    openssl:         1.0.2h-vc14_2     conda-forge [vc14]
    pyparsing:       2.1.7-py35_0      conda-forge
    pyqt:            4.11.4-py35_7
    python-dateutil: 2.5.3-py35_0      conda-forge
    pytz:            2016.6.1-py35_0   conda-forge
    qt:              4.8.7-vc14_9                  [vc14]
    sip:             4.18-py35_0       conda-forge
    six:             1.10.0-py35_0     conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    jpeg:            9b-vc14_0         conda-forge [vc14] --> 8d-vc14_0    [vc14]
    libtiff:         4.0.6-vc14_6      conda-forge [vc14] --> 4.0.6-vc14_2 [vc14]

Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
```

**Comment by hadim** [comment]
I found the culprit. `qt` depends on : 

```
dependencies:
    jpeg 8d
    libpng 1.6*
    libtiff 4.0.*
    openssl 1.0.2*
    zlib 1.2.*
```

**Comment by jakirkham** [comment]
So the `qt` package comes from `defaults`. Hence why it is not listed as coming from `conda-forge` above. We don't build `qt` anywhere, but Linux ATM. See issue ( https://github.com/conda-forge/conda-forge.github.io/issues/169 ).

**Comment by jakirkham** [comment]
In any event, this is not an `opencv` issue. This is an org pinning issue that has been causing pain for some time unfortunately.

**Comment by 183amir** [comment]
Opencv can have another branch that builds with jpeg 8 and would not break anybody's workflow. 
I suggested this before but it was disregarded.

**Comment by shelper** [comment]
then can anyone add opencv with jpeg8 to conda-forge?

**Comment by patricksnape** [comment]
You are welcome to add a PR

**Comment by 183amir** [comment]
> then can anyone add opencv with jpeg8 to conda-forge?

This is possible but discouraged. The solution so far is to bring what you have compiled under jpeg8 here to conda-forge and compile it with jpeg9.
More similar discussions here: https://github.com/conda-forge/boost-feedstock/pull/15 and https://github.com/conda-forge/jasper-feedstock/pull/12

**Comment by shelper** [comment]
conda-forge has jpeg9 for 32bit, but not 64bit
see below:



>  jpeg 9b vc10_0
> --------------
> file name   : conda-forge::jpeg-9b-vc10_0.tar.bz2
> name        : jpeg
> version     : 9b
> build number: 0
> build string: vc10_0
> channel     : conda-forge/win-64
> size        : 297 KB
> arch        : x86_64
> binstar     : {'package_id': '57113611752ed06038dfe854', 'owner_id': '5528f42ce1dad12
> 974506e8d', 'channel': 'main'}
> features    : vc10
> fn          : jpeg-9b-vc10_0.tar.bz2
> license     : Custom free software license
> machine     : x86_64
> md5         : 16d13c0ff3f70aeb3985c41e90a9889b
> operatingsystem: win32
> platform    : win
> priority    : 2
> schannel    : conda-forge
> subdir      : win-64
> target-triplet: x86_64-any-win32
> url         : https://conda.anaconda.org/conda-forge/win-64/jpeg-9b-vc10_0.tar.bz2
> dependencies:
> 
> jpeg 9b vc14_0
> --------------
> file name   : conda-forge::jpeg-9b-vc14_0.tar.bz2
> name        : jpeg
> version     : 9b
> build number: 0
> build string: vc14_0
> channel     : conda-forge/win-64
> size        : 301 KB
> arch        : x86_64
> binstar     : {'package_id': '57113611752ed06038dfe854', 'owner_id': '5528f42ce1dad12
> 974506e8d', 'channel': 'main'}
> features    : vc14
> fn          : jpeg-9b-vc14_0.tar.bz2
> license     : Custom free software license
> machine     : x86_64
> md5         : 84096b1f3fddf28e165117590fcad7b4
> operatingsystem: win32
> platform    : win
> priority    : 2
> schannel    : conda-forge
> subdir      : win-64
> target-triplet: x86_64-any-win32
> url         : https://conda.anaconda.org/conda-forge/win-64/jpeg-9b-vc14_0.tar.bz2
> dependencies:
> 
> jpeg 9b vc9_0
> -------------
> file name   : conda-forge::jpeg-9b-vc9_0.tar.bz2
> name        : jpeg
> version     : 9b
> build number: 0
> build string: vc9_0
> channel     : conda-forge/win-64
> size        : 294 KB
> arch        : x86_64
> binstar     : {'package_id': '57113611752ed06038dfe854', 'owner_id': '5528f42ce1dad12
> 974506e8d', 'channel': 'main'}
> features    : vc9
> fn          : jpeg-9b-vc9_0.tar.bz2
> license     : Custom free software license
> machine     : x86_64
> md5         : b73350bd1d7e5381760ab5e9bf4edb58
> operatingsystem: win32
> platform    : win
> priority    : 2
> schannel    : conda-forge
> subdir      : win-64
> target-triplet: x86_64-any-win32
> url         : https://conda.anaconda.org/conda-forge/win-64/jpeg-9b-vc9_0.tar.bz2
> dependencies:

**Comment by jakirkham** [comment]
If there are issues with the `jpeg` packages, please raise them at the [`jpeg` issue tracker]( https://github.com/conda-forge/jpeg-feedstock/issues ). Thanks.
