### ISSUE TITLE
Upstream OpenCV 3.1 on mac has bug that causes it to crash 100s after opening a videocapture device

### ISSUE THREAD

**Issue by mshunshin** [conda-forge/opencv-feedstock#28]
The upstream OpenCV 3.1 when compiled on mac has a bug that causes it to crash (in C++ and python wrappers) after 100s after opening a video capture device. As this is the most common reason for using OpenCV it is rather limiting.

This original issue is here:
https://github.com/opencv/opencv/issues/5874

The patch is simple, just chainging one timer line:

https://github.com/opencv/opencv/pull/6051

Would it be possible to please incorporate this patch.

If you did I think conda-forge would have the first useful OpenCV 3.1 in anaconda for the mac.

**Comment by jakirkham** [comment]
Please open a PR.

**Comment by jakirkham** [comment]
Hopefully once we package 3.2.0 this will be solved. Closing this out.
