### ISSUE TITLE
AppVeyor failures

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/opencv-feedstock#3]
It seems that Win64 builds are failing:

```shell
// If this value is on, makefiles will be generated without the .SILENT directive, and all commands will be echoed to the console during the make.  This is useful for debugging only. With Visual Studio IDE projects all commands are done without /nologo.
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
 
 
Microsoft (R) Visual C++ Express Edition Version 9.0.30729.1.
Copyright (C) Microsoft Corp 2007. All rights reserved.
 
The following files were specified on the command line:
 
	OpenCV.sln
 
These files could not be found and will not be loaded. 
Microsoft (R) Visual C++ Express Edition Version 9.0.30729.1.
Copyright (C) Microsoft Corp 2007. All rights reserved.
 
The following files were specified on the command line:
 
	OpenCV.sln
 
These files could not be found and will not be loaded.Command failed: C:\windows\system32\cmd.exe /c call bld.bat
Command exited with code 1
```

**Comment by patricksnape** [comment]
`amd64` build target is not being correctly created:

```
C:\conda\conda-bld\work\opencv-2.4.12>call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat" amd64 
The specified configuration type is missing.  The tools for the
configuration might not be installed.
```

**Comment by jakirkham** [comment]
Are you referring to the patch for VS 2008 64-bit support? That is currently not applied against this. Though it can be. :smile:

However, we are seeing failures for VS versions that should have 64-bit support too.

**Comment by patricksnape** [comment]
Yes I was just highlighting the issue :) - It is indeed due to the missing patch. Are we seeing failures we are not supposed to? I don't think so, this is all Python 2.7 builds?

**Comment by jakirkham** [comment]
Forgot it was Python 2.7 only. :laughing:

Yes, I can patch it when I'm back in front of my computer.

**Comment by jakirkham** [comment]
Sorry for the long turnaround here. See this PR ( https://github.com/conda-forge/opencv-feedstock/pull/4 ) for the fixes.

**Comment by jakirkham** [comment]
Fixed by ( https://github.com/conda-forge/opencv-feedstock/pull/4 ). However, there are many image library dependencies here. We are going to need to pin them for everything to work correctly here.

cc @pelson
