### ISSUE TITLE
OpenCV 3.1 FLANN Matcher Patch not included?

### ISSUE THREAD

**Issue by jlaura** [conda-forge/opencv-feedstock#31]
First, thanks for getting openCV3 into conda forge!  It looks like opencv3.1 needs to be patched, though I am not 100% sure where to apply the patch (or I would open a PR).  The issue is document [here](https://github.com/opencv/opencv/issues/5667) and @patricksnape offered up a solution.  I think that OpenCV3.1 pulling using a release tag means that the patch was never applied upstream and needs to be applied in the recipe?

If it is easier to aim me in the direction of the fix I am happy to get a PR started.

Error occurs on: https://travis-ci.org/USGS-Astrogeology/autocnet/jobs/161758571#L841
Sanity check to make sure that the Conda-Forge OpenCV is being pulled down: https://travis-ci.org/USGS-Astrogeology/autocnet/jobs/161758571#L430

Edit to include a link to what I **think** the patch file should be: https://patch-diff.githubusercontent.com/raw/opencv/opencv/pull/6009.patch

**Comment by patricksnape** [comment]
As is mentioned in #29, I am unwilling to apply upstream patches that are not in a tagged version (other than those that fix **build** errors only). If you would like to see that patch in a release version of OpenCV, please apply pressure to the OpenCV upstream maintainers to release 3.2 :smile:

**Comment by jlaura** [comment]
@patricksnape I completely understand why you do not want to start including all of these patches.  It is unfortunate though that this feedstock has > 1100 downloads via anaconda.org and is almost a year out of date.  To try and help remedy that, I open [an issue upstream](https://github.com/opencv/opencv/issues/7329).  Thanks to all of the conda-forge OpenCV maintainers, you are saving the larger community a ton of time building and distributing OpenCV.

**Comment by jakirkham** [comment]
Going to close this out, hoping that once we package 3.2.0 this is solved.
