### ISSUE TITLE
Add opencv as a core dependency package?

### ISSUE THREAD

**Issue by dstansby** [conda-forge/opencv-feedstock#335]
### Comment:

I've just been testing https://github.com/conda-forge/sunpy-feedstock, which now depends on opencv for testing. We have run up against the error in this issue: https://github.com/conda-forge/opencv-feedstock/issues/321.

The conda-forge docs say (https://conda-forge.org/docs/maintainer/adding_pkgs.html#avoid-external-dependencies):

> As a general rule: all dependencies have to be packaged by conda-forge as well. This is necessary to assure [ABI](https://conda-forge.org/docs/misc/00_intro.html#term-ABI) compatibility for all our packages.
> There are only a few exceptions to this rule:
> Some dependencies have to be satisfied with [CDT](https://conda-forge.org/docs/misc/00_intro.html#term-CDT) packages (see [Core Dependency Tree Packages (CDTs)](https://conda-forge.org/docs/maintainer/knowledge_base.html#cdt-packages)).

From reading the conda-forge docs it seems like opencv should be packaged as a Core Dependency Tree Package, not a normal feedstock package. To avoid the libGL linking error should opencv be added as a Core Dependency Tree package instead of living here as a normal feedstock?

**Comment by hmaarrfk** [comment]
I think the conversion here https://github.com/conda-forge/opencv-feedstock/issues/293 is relevant.

**Comment by hmaarrfk** [comment]
I'm going to close this since I think 293 is the relevant issue. let me know if you disagree.
