### ISSUE TITLE
cv2.version module

### ISSUE THREAD

**Issue by jamesmyatt** [conda-forge/opencv-feedstock#343]
The PyPI wheel include a `cv2.version` module, which is created at build-time using [`find_version.py`](https://github.com/opencv/opencv-python/blob/4.x/find_version.py). See https://github.com/opencv/opencv-python/tree/4.x#versioning. Would it be possible to include the same logic in the conda packages? Would it be a good idea? Parity with the pypi wheel seems like a good idea to me.

Most of all, I'm interested to in the `cv2.version.headless` attribute that shows whether cv2 has been compiled with the headless options or not.

**Comment by hmaarrfk** [comment]
I (and likely other maintainers) would accept patches to conda-forge to improve things on this front. I would ask that an attempt is made to upstream them.

The last one we tried to upstream was stalled: https://github.com/opencv/opencv/pull/21611 but I think that if you add your voice for more "official" support for these features, it would go a long way.

**Comment by mshabunin** [comment]
> Most of all, I'm interested to in the cv2.version.headless attribute that shows whether cv2 has been compiled with the headless options or not.

AFAIK there is no separate headless OpenCV package in conda-forge, see #293

Version string can be accessed directly as `cv2.__version__` and more detailed information can be extracted from `cv2.getBuildInformation()`

**Comment by hmaarrfk** [comment]
I would like to close this as it seems that an adequate workaround was found.

Please feel free to re-open if you think there is an important usecase that you want to tackle.

We've recently released "headless" versions of opencv and would welcome feedback on them.
