### ISSUE TITLE
Would it be possible to build recent (>=4.6.0) opencv with protobuf <3.20?

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/opencv-feedstock#356]
### Comment:

I would like to install opencv with tensorflow on Windows, but tensorflow (at least as of version 2.11) wants protobuf <3.20.  Would it be possible to build (lib)opencv 4.6.0 or 4.7.0 with protobuf <3.20?

**Comment by hmaarrfk** [comment]
Unfortunately, buliding out too many "options" leads to alot of churn from the maintenance side.

can you please share your usecase, h-vetinari has been working hard on protobuf and we have not seen any challenges installing modern protobufs with most packages.

Understanding your usecase may help us find a solution forward.

**Comment by DManowitz** [comment]
At the moment I'm just experimenting, but I would like to be able to use Tensorflow with GPU support on native Windows, which requires Tensorflow <2.11, and these versions of Tensorflow require protobuf <3.20.

**Comment by hmaarrfk** [comment]
I guess i should expand to say that if you just want to experiment, the best way is to get your local build environment up and runnign and to update the file
https://github.com/conda-forge/opencv-feedstock/pull/386

and use
```
conda build -m .ci_support\... recipe
```

and upload the packages you need to your own channel. that cuts all the review time.

If we can write the extra builds you need in a recipe i'm more open to it. given there is enough comments surrounding it.

**Comment by hmaarrfk** [comment]
closing this as it is likely stale.
