### ISSUE TITLE
Does this channel provide opencv-contrib as well?

### ISSUE THREAD

**Issue by Coderx7** [conda-forge/opencv-feedstock#376]
### Comment:

Hi, I was curious to know if conda also provides `opencv-contrib` ?  I couldn't find one by doing a conda search with opencv.  
I know `opencv-contrib-python` can be installed using pip, but currently, there's an issue in the `Anaconda` distribution that causes errors such as the following : 
```
QObject::moveToThread: Current thread (0x1697a40) is not the object's thread (0x16e70b0).
Cannot move to target thread (0x1697a40)
```
where its caused by Qt library mismatch between them. you don't get this error if you install opencv using conda though. 
so for the time being, using conda to install opencv seems to be the right thing . however I noticed theres no opencv-contrib here, so I was wondering if there's one at all?

**Comment by hmaarrfk** [comment]
Yes it seems that we package everything into a single package:
https://github.com/conda-forge/opencv-feedstock/blob/main/recipe/meta.yaml#L41

Please do not mix and match the default channel and the conda-forge channel. 

Create a fully new environment if you wish to test conda-forge packages, especially opencv.

**Comment by Coderx7** [comment]
> Yes it seems that we package everything into a single package: https://github.com/conda-forge/opencv-feedstock/blob/main/recipe/meta.yaml#L41
> 
> Please do not mix and match the default channel and the conda-forge channel.
> 
> Create a fully new environment if you wish to test conda-forge packages, especially opencv.

Thanks a lot, so I should always install it like this:
```
conda install -c conda-forge opencv 
```
to get the `opencv-contrib-python` equivalent right? 
by the way is there a specific reason why the default version is 4.6.0 when I initiate the installation without specifying a version number? I assumed it would always install the latest version. when I tried to install opencv, it installed 4.6.0. 
Thanks a lot in advance
