### ISSUE TITLE
Usage of HIGHGUI

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/opencv-feedstock#389]
### Comment:

Does any user use HighGUI?

I'm thinking of de-prioritizing the HighGUI build and making the no-gui the "default".

mostly it is to help with the qt6 transition.

I'm curious to see if anybody uses it. I know this is "issue" is a bad way to poll users, not too sure if there exists a better way.

**Comment by traversaro** [comment]
My group use it quite a lot, it is commonly used to build ad-hoc guis for experiments or data processing tasks. 

> I'm thinking of de-prioritizing the HighGUI build and making the no-gui the "default".

If this is done, how do yu imagine one should install the with-gui build? With a specific build string selector? Thanks!

**Comment by hmaarrfk** [comment]
> With a specific build string selector? Thanks!

I really dislike teaching and pointing people to build strings.

Good to know that you are using it. 

Does your group have any reservations about qt6?

**Comment by traversaro** [comment]
> Does your group have any reservations about qt6?

No specific reservation. There are some still softare of ours that needs to be updated, but based on past experience of that kind of migrations I am not too afraid of it.

**Comment by hmaarrfk** [comment]
Maybe we can sync up the qt6 migration with a version bump of opencv.

**Comment by hmaarrfk** [comment]
Closed in favor of https://github.com/conda-forge/opencv-feedstock/issues/293
