### ISSUE TITLE
Add typestubs

### ISSUE THREAD

**Issue by ethanc8** [conda-forge/opencv-feedstock#421]
### Comment:

OpenCV automatically generates Python typestubs that can be used to get intelligent autocompletion in IDEs when using OpenCV. However, I don't get any typestubs when using the conda-forge packages. Are they located in a different package, and if not, can they be added to the packages?

**Comment by traversaro** [comment]
See https://github.com/conda-forge/opencv-feedstock/issues/374 . I guess the typestub generation needs to be enabled and the typestub correctly installed.

**Comment by ethanc8** [comment]
Oh, then this is a duplicate of #374.

**Comment by ethanc8** [comment]
Oops, should be closed as "not planned".

**Comment by ethanc8** [comment]
Oops, should be closed as "not planned".
