### ISSUE TITLE
opencv3

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/opencv-feedstock#5]
@183amir commented on [Tue Apr 19 2016](https://github.com/conda-forge/staged-recipes/issues/407)

Hi everyone,

Are we going to have opencv3 in conda-forge? If yes, could someone who has experience please do it?
Maybe @jakirkham you can do it?

---

@jakirkham commented on [Tue Apr 19 2016](https://github.com/conda-forge/staged-recipes/issues/407#issuecomment-212172394)

Probably, but not in the near term. I have some other obligations I need to work on first.

**Comment by jakirkham** [comment]
Note @183amir, we do have OpenCV 2 currently. Though a PR to get OpenCV 3 is welcome. We will likely maintain both versions for now. At present, I don't have time to focus on this though. So, if you would like to get the ball rolling, maybe you could try making a PR against `master` here and see how far you get.

**Comment by patricksnape** [comment]
I have a working recipe for opencv3 on my menpo channel. Can migrate it.

**Comment by jakirkham** [comment]
That would be awesome. Give me a couple of seconds and then I can go through what we need to do.

**Comment by jakirkham** [comment]
So, go ahead and add the recipe in a branch in your fork and PR it here against `master`. From now on, we will use 2 branches for releases. There is a `v2` branch now, which we PR against from our own forks with OpenCV 2.x fixes. From now on, `master` will contain OpenCV 3.x. If we need more granularity than that, we can add more branches.

**Comment by patricksnape** [comment]
Just a note that if we do this then everyone will have to special case using OpenCV2 - which is by far the most commonly used OpenCV version. OpenCV2 and OpenCV3 are not backwards compatible (hence the major version number) but OpenCV3 still lives in the OpenCV2 namespace (who knows why). Are we happy with this? There could be a lot of very confused people since OpenCV2 is still receiving updates...

**Comment by 183amir** [comment]
Yes, we use opencv2 too and it is important for us too they have different package names.

**Comment by jakirkham** [comment]
> Just a note that if we do this then everyone will have to special case using OpenCV2 - which is by far the most commonly used OpenCV version. OpenCV2 and OpenCV3 are not backwards compatible (hence the major version number) but OpenCV3 still lives in the OpenCV2 namespace (who knows why).

What we can do is pin things that need OpenCV2 by doing `opencv 2.*` or similar.

There is some code floating around recently to aid in this pinning in conda-forge. We are trying to find it a home still.

Can you think of any cases that pinning wouldn't work? The only package at conda-forge that uses OpenCV is caffe and I pinned it to 2.x because I figured this would eventually happen. If there are other packages you plan to add that will be affected, we can certainly address them as they are added.

> Are we happy with this?

We will continue to update both OpenCV 2.x and 3.x so this isn't a problem AFAICT. That's the beauty of having them in two branches. So, this should remain really straightforward and it won't force anyone into either version.

> There could be a lot of very confused people since OpenCV2 is still receiving updates...

Having a couple major releases maintained is not uncommon with large software projects. OpenCV is no different in this regard. It seems fair if we adapt to their model and provide those maintained releases and let people choose what works for them.

If people get confused and we happen to run into them either on a issue here or elsewhere, we can always politely explain the situation and give them some friendly advice.

**Comment by msarahan** [comment]
@patricksnape I think we can further simplify the recipe we came up with for OpenCV 3 - please ping me when you submit it.  Add me as a maintainer if you want.

**Comment by jakirkham** [comment]
Added you in this PR ( https://github.com/conda-forge/opencv-feedstock/pull/11 ), @msarahan.

**Comment by 183amir** [comment]
@patricksnape I would appreciate it if you could add opencv 3 here.

**Comment by AbdealiJK** [comment]
@patricksnape I'd appreciate the OpenCV 3 recipe added here too :)

**Comment by JuanCab** [comment]
Another vote for OpenCV3 support since none of the existing conda installable versions of opencv 3.1.0 appear to be terribly functional.

**Comment by patricksnape** [comment]
Added via #16.
