### ISSUE TITLE
Python 3.5 installation (missing ffmpeg) - Windows x64

### ISSUE THREAD

**Issue by franktoffel** [conda-forge/opencv-feedstock#52]
I managed to install OpenCV 3.1 using conda and Python 3.5 and everything seems to work fine using the conda-forge channel.

However, when I tried to import a video file via ffmpeg I got this:

    import numpy as np
    import cv2

    cap = cv2.VideoCapture('data\vtest.avi')
    cap.read()
    
    #(False, None)

When using still images or my laptop webcam it works (notice that the VideCapture returns `None`). Thus, something is wrong with ffmpeg.

I have tried a couple of things:

 1. Install ffmpeg also using the conda-forge channel (works fine separately
but apparently OpenCV cannot call it since it looks for specific dlls).
 2. Installing opencv from the menpo channel (this one includes ffmpegs dlls and works).

Am I missing something to install ffmpeg properly for opencv?

**Comment by patricksnape** [comment]
This is not built against FFMPEG at the moment, so this is expected behaviour. OpenCV is extremely difficult to build and Windows is a real endeavour to get working. Please feel free to open a pull request that adds a working FFMPEG build.

**Comment by patricksnape** [comment]
Latest build contains FFMPEG
