### ISSUE TITLE
Hard coded path

### ISSUE THREAD

**Issue by rpep** [conda-forge/opencv-feedstock#55]
Running the first block of code from [here](http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_objdetect/py_face_detection/py_face_detection.html#face-detection)
gives an error that looks as though it's to do with hard coded paths in the building of OpenCV.

```
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in ipp_cvtColor, file /Users/travis/miniconda3/conda-bld/work/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7456
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: /Users/travis/miniconda3/conda-bld/work/opencv-3.1.0/modules/imgproc/src/color.cpp:7456: error: (-215) scn == 3 || scn == 4 in function ipp_cvtColor
```

**Comment by patricksnape** [comment]
No, that is failing because you must change the paths to be absolute. This is not a build bug.
