### ISSUE TITLE
Need GTK support opencv ; problem which imshow()

### ISSUE THREAD

**Issue by connect2robiul** [conda-forge/opencv-feedstock#56]
When I try to install, I get this 

`UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv -> numpy 1.7* -> python 2.6* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.`

the spcific error is 

`install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage`

**Comment by patricksnape** [comment]
Those two errors seems to be unrelated?

**Comment by oxydron** [comment]
Yeah, seems to be 2 problems:
1. The biggest opencv problem of all times: the "gtk 2.x or carbon error" when trying to use cv2.imshow()
2. Conflicted packages.
I'm looking to solve the first problem for 2 weeks...

**Comment by patricksnape** [comment]
We don't support installing gtk2 from this package (at the moment). But I will take a look whenever I finally get opencv 3.2.0 building

**Comment by patricksnape** [comment]
@jakirkham do we have any other packages that link against GTK?

**Comment by connect2robiul** [comment]
How to fixed this?  Any idea @patricksnape

**Comment by jakirkham** [comment]
Maybe Qt. Even if we were using GTK, I think it would be coming from the system. I don't believe there is a GTK package in `defaults` (haven't checked though). A quick [search in the org]( https://github.com/search?p=1&q=org%3Aconda-forge+GTK&type=Code ) seems to suggest most things are not using GTK instead of using it.

**Comment by oxydron** [comment]
@jakirkham Ok, using Qt, could you point some directions? Any conda install command? Any pip or apt-get install? Any tip?

**Comment by jakirkham** [comment]
Sorry @oxydron. That was in response to @patricksnape.

**Comment by patricksnape** [comment]
So if we have no existing GTK packages then this won't get built with GTK until we do

**Comment by jakirkham** [comment]
@patricksnape is absolutely correct. AFAIAC there is nothing actionable for us here without a GTK package. So am going to close that out. That said, if the community adds a GTK package, we can reopen and discuss building it here.

**Comment by jakirkham** [comment]
Opened issue ( https://github.com/conda-forge/staged-recipes/issues/3914 ) to track adding GTK to conda-forge. Once that is addressed, we can revisit building OpenCV with GTK support.

**Comment by salmedina** [comment]
Any update on this problem?

**Comment by jakirkham** [comment]
The package got rebuilt with `qt` support a long time ago. Would recommend opening a new issue with more details if you are running into problems. Thanks.
