### ISSUE TITLE
Suggestion to use opencv-python wheels

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/opencv-feedstock#57]
Would if be feasible to use the opencv-python wheels for this package?

That would move some of the maintenance burden off of conda-forge?

@jakirkham thoughts?

**Comment by jakirkham** [comment]
I'd rather not. It feels like a step backwards as we are moving from building from source to repackaging a binary. The latter is something that is already pretty strongly discouraged in conda-forge.

That said, I agree that building OpenCV is a pain. So if you have other ideas about how to make it less of a pain I'd be interested. 😄

**Comment by patricksnape** [comment]
It would be much better if we could get @skvark involved in building OpenCV here since he seems to have a load of experience in getting the nightmare that is OpenCV to build on all platforms!

https://github.com/skvark/opencv-python

**Comment by jakirkham** [comment]
So I think the main source of maintenance burden has been Python 2.7. If OpenCV will start doing CI testing for VS 2008, then things would get a lot better. Alternatively if they would drop Python 2.7 support, that would help too. We have been discussing this with them upstream ( https://github.com/opencv/opencv/issues/8481 ). Based on the outcome of that discussion, we can determine what we will do here.

**Comment by jakirkham** [comment]
It sounds like OpenCV won't support standard Python 2.7 on Windows. As such we will drop support for it in the future as well. ( https://github.com/conda-forge/opencv-feedstock/issues/71 ) TBH this was a sizable amount of the maintenance burden. So this should make it easier to package releases in the future. In light of this, I think we can close this out.
