### ISSUE TITLE
Remove VS fixes once Conda build 1.20.1 is released

### ISSUE THREAD

**Issue by patricksnape** [conda-forge/opencv-feedstock#6]
Remove the [conda-smithy hack](https://github.com/conda-forge/opencv-feedstock/commit/b40ac1262269b515142a8134a169af64a72d1120) for VS9 once the new conda-build is [released](https://github.com/conda/conda-build/pull/861).

**Comment by jakirkham** [comment]
This PR ( https://github.com/conda-forge/opencv-feedstock/pull/10 ) should fix it.

**Comment by jakirkham** [comment]
Apparently, 1.20.1 is not sufficient for solving this problem. Please look at this PR ( https://github.com/conda-forge/opencv-feedstock/pull/10 ) for an example of the failures one gets.

**Comment by jakirkham** [comment]
Basically, we need to start using `nmake` according to this [comment]( https://github.com/conda-forge/opencv-feedstock/pull/10#issuecomment-215949989 ).

**Comment by patricksnape** [comment]
This is not a problem on master, but the v2 branch still needs updating

**Comment by jakirkham** [comment]
I think we ended up removing these at some point as that branch has been failing on 64-bit for a while. I'll try to add a PR that uses `nmake`.

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/opencv-feedstock/pull/34 ), which tries to use `nmake`.

**Comment by jakirkham** [comment]
Yeah we should totally do this now. `conda-forge-build-setup` already adds those patches anyways.

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/opencv-feedstock/pull/47 ) and PR ( https://github.com/conda-forge/opencv-feedstock/pull/48 ) for cleaning out these files.

**Comment by patricksnape** [comment]
Fixed as of #50
