### ISSUE TITLE
Library not loaded openbasp

### ISSUE THREAD

**Issue by bcvanmeurs** [conda-forge/opencv-feedstock#64]
When trying to update to version 3.2.0, in a virtual environment on MacOS, I got the following error when importing cv2:

ImportError: dlopen(/Users/bramvanmeurs/anaconda3/envs/smartsensing/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/bramvanmeurs/anaconda3/envs/smartsensing/lib/libopencv_hdf.3.2.0.dylib
  Reason: image not found

conda install openblas didn't solve the issue. Version 3.1.0 is working fine though. Thanks in advance

**Comment by zym1010** [comment]
looks that this opencv is linked with openblas 0.2.19. Do you have that installed?

**Comment by zym1010** [comment]
@jakirkham it should not be the case that opencv is directly linked to openblas, right?

**Comment by patricksnape** [comment]
`conda install -c conda-forge numpy` fixes it. Looks like OpenCV does link against OpenBlas because numpy brings openblas in. @jakirkham I guess this needs to have blas as a feature?

**Comment by jakirkham** [comment]
Interesting, though I guess it makes sense that OpenCV would use a BLAS. Yes, we need to update it to use the BLAS feature.

**Comment by bcvanmeurs** [comment]
Thanks! I retried, and it works. Great work, guys!
