### ISSUE TITLE
JPEG and other pinning

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/opencv-feedstock#7]
This also needs pinning. Could we get a PR started on this, @pelson? I want to see how bad the situation is. I don't think it is too bad as I rebuilt it yesterday without issues.

**Comment by pelson** [comment]
Done in https://github.com/conda-forge/opencv-feedstock/pull/8 and https://github.com/conda-forge/opencv-feedstock/pull/9

**Comment by jakirkham** [comment]
Thanks @pelson.

**Comment by jakirkham** [comment]
So, this went smoothly and has been done. New packages are being deployed. We have fewer problems here as Python 3 is not supported, but things may change when that happens.
