### ISSUE TITLE
Python 2.7 on Windows

### ISSUE THREAD

**Issue by patricksnape** [conda-forge/opencv-feedstock#71]
Just dropping this note here so say that, since upstream no longer supports Visual Studio 2008, we no longer support Python 2.7 after OpenCV 3.2.

https://github.com/opencv/opencv/issues/8481

**Comment by jakirkham** [comment]
Thanks for noting this @patricksnape.

TBH there are other libraries like some of those in Jupyter that are dropping Python 2 outright. So this doesn't seem like an unreasonable thing for OpenCV to do.

Looking forward to much less work on our heads in the future. 😄
