### ISSUE TITLE
cv2.imshow does not work 

### ISSUE THREAD

**Issue by hajapy** [conda-forge/opencv-feedstock#79]
Version:
`opencv 3.2.0 np111py35_blas_openblas_203 [blas_openblas] conda-forge`

OS: 
`4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Minimal example and error message:
```
import cv2
import numpy as np
cv2.imshow('im', np.random.rand(100, 100, 3))

OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /feedstock_root/build_artefacts/opencv_1496431267672/work/opencv-3.2.0/modules/highgui/src/window.cpp, line 583
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-3-3962acc7e460> in <module>()
----> 1 cv2.imshow('im', np.random.rand(100, 100, 3))

error: /feedstock_root/build_artefacts/opencv_1496431267672/work/opencv-3.2.0/modules/highgui/src/window.cpp:583: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

```

Would it be possible to bring in QT 4.8.7 as a build and run dependency and build with cmake flag -DWITH_QT=4 if Linux, DWITH_QT=0 if Darwin? If so, I'm happy to open a pull request.

**Comment by jakirkham** [comment]
As asked in the PR, why Qt4? Also why not macOS and what about Windows?

**Comment by hajapy** [comment]
On the whole I agree with the sentiment (from PR comments) that the build should give a consistent experience across platforms. That is not currently the case, on OS X cv2.imshow() works with the latest build, but it fails on Linux and I am not able to test it in Windows.

The main reason this PR used qt 4 is that it has worked for me previously on a similar recipe to build opencv 3.1.0. I'd be willing to try it with qt 5.6.2 
On Mac OS, with QT 4 enabled cv2.imshow() behaved poorly. The behaviour we get with the default Cocoa support was much better. 
Windows: I have no way to test builds, so I left as-is for now.

**Comment by hajapy** [comment]
I closed the PR with qt4 for linux-only and opened a PR with qt5 for all platforms. It should address your concerns about the original approach.
