### ISSUE TITLE
Unable to run a simple image detection program

### ISSUE THREAD

**Issue by Hamsini92** [conda-forge/opencv-feedstock#83]
Hi , 
I have insatlled Opencv3 in anaconda. However, the program gave me the below error . 

**File "C:/Users/Hamsini Sankaran/.spyder-py3/temp.py", line 3, in <module>
    cv2.imshow("Original",image)

error: ..\..\..\modules\highgui\src\window.cpp:281: error: (-215) size.width>0 && size.height>0 in function cv::imshow**

**Below is my code  import cv2**
image = cv2.imread('D:\CV\rose.jpeg')
cv2.imshow("Original",image)
cv2.waitkey(0)

Please could anyone of you clarify , since I am new to openCV 
Thanks and Regards,
Hamsini Sankaran

**Comment by patricksnape** [comment]
This is not an OpenCV support forum - that error doesn't look like a build error so I am closing this. Please look for support on the OpenCV respository.
