### ISSUE TITLE
new link to missing libavresample.so.3 in linux-64/opencv-3.2.0-np113py27_blas_openblas_203

### ISSUE THREAD

**Issue by elelayan** [conda-forge/opencv-feedstock#84]
now `import cv2` fails with `ImportError: libavresample.so.3: cannot open shared object file: No such file or directory`.
```bash
ldd lib/python2.7/site-packages/cv2.so|grep avres
	libavresample.so.3 => not found
```

**Comment by patricksnape** [comment]
What version of ffmpeg do you have installed?

**Comment by elelayan** [comment]
I don't have any installed.
I didn't require any until now.
Do you mean it's a new dependency ? And it's not available via conda ?

**Comment by patricksnape** [comment]
It is available - and it is now required - please run `conda install -c conda-forge ffmpeg`

**Comment by elelayan** [comment]
Sorry: I'm new to conda and was expecting `conda update -r requirements.txt` to install new required dependencies.
Thanks for your help.
