### ISSUE TITLE
Rtp protocol not on ffmpeg whitelist

### ISSUE THREAD

**Issue by Mosie1** [conda-forge/opencv-feedstock#86]
I'm getting the following error when trying to open an rtp stream using an sdp-file 
`cap = cv2.VideoCapture("sololink.sdp")`

error:
`[rtp @ 000002bb4a022ec0] Protocol not on whitelist 'file,crypto'!`
`warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:779)`
`warning: sololink.sdp (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:780)`

I get the same result on windows and linux. On linux i don't get the error when i sudo the python script.

**Comment by patricksnape** [comment]
Sorry, I'm not able to debug what feels like an OpenCV specific issue. Please contact the OpenCV developers and then point me to how I can change the build script to fix this.
