### ISSUE TITLE
Can't enable FFMPEG support for OpenCV

### ISSUE THREAD

**Issue by jackersson** [conda-forge/opencv-feedstock#88]
Hi, 

Problem:
After installation OpenCV using commands in Readme - can't work with cv2.VideoCapture(). 
run_test.py for FFMPEG support is not passing.

Has anyone solved this problem?

**Comment by magsol** [comment]
I believe you have to install ffmpeg yourself for that to work, before installing OpenCV. What platform (operating system) are you using?

**Comment by ynandwan** [comment]
Still not working, even after I tried installing opencv after ffmpeg -
conda install -c conda-forge ffmpeg 
conda install -c conda-forge opencv
 
Operating system - OSX - El Capitan, version - 10.11.6

**Comment by ynandwan** [comment]
I figured out that it works for only those videos that QuickTime Player is able to open. QuickTime was not able to play any video that I downloaded for background subtraction test from http://www.cvc.uab.es/~bagdanov/master/videos.html.  
In order to test, I recorded a video using webcam, verified that QuickTime is able to open it and VideoCapture worked with it. 
@jackersson , could you try this?

**Comment by chukkwagon** [comment]
I am having the same problem as @jackersson.

System: Ubuntu 17.04, Anaconda 4.3.21

```
conda create --name cv python=2.7 scipy=0.17 numpy=1.11
conda config --add channels conda-forge
conda install -c conda-forge ffmpeg
conda install -c conda-forge opencv=2.4.13
```

python test that is failing:

```
def test_load_mp4_videos(self):
        import cv2
        video = cv2.VideoCapture("turtle.mp4")
        okay, frame = video.read()
        self.assertTrue(okay, "Loading mp4 video failed")```

`turtle.mp4` is in the same directory as the test file, so I'm confident that this is not a path issue. Any ideas?

**Comment by patricksnape** [comment]
I'm not sure when the last time we updated OpenCV 2.x was - so I can't guarantee that FFMPEG works properly for OpenCV 2.x

**Comment by Abramjos** [comment]
It seems like we have to build opencv with FFMPEG=yes/1
only then we can do it right and I am not sure about how.
opencv3 worked perfect anyway

**Comment by patricksnape** [comment]
New OpenCV v2 build that includes FFMPEG now released (will take around an hour to appear)

**Comment by chrisjlondon** [comment]
Hi Patrick,
Can you post a link to the new OpenCV v2 build that includes FFMPEG?
Thx

**Comment by jakirkham** [comment]
It’s the latest version of 2 (2.4.13.4).

**Comment by chrisjlondon** [comment]
Ah, ok, thanks. Does it mean that this is still not working in  OpenCV v3.3?

**Comment by jakirkham** [comment]
I don’t follow. I thought you wanted a copy of OpenCV 2 with FFMPEG support. Are you wanting a copy of OpenCV 3 instead?

**Comment by chrisjlondon** [comment]
Sorry, yes, I am looking for OpenCV3 with FFMPEG support.  In the OpenCV version that I have (3.3.0) cv2.VideoCapture works fine with mp4 files, but not with avi files.
Thanks

**Comment by jakirkham** [comment]
Would make sure you have the latest build number as well 202.

**Comment by jakirkham** [comment]
If that doesn’t solve it, would open a new issue.

**Comment by patricksnape** [comment]
If specific file formats aren’t working I would try Renecoding the video and check it isn’t an unsupported codec version

**Comment by jacktkk** [comment]
@chrisjlondon
sorry for bothering u !
I installed opencv3 by "conda install -c https://conda.binstar.org/menpo opencv3"
However cv2.VideoCapture even doesn't work fine with mp4 files.
 I am new to the opencv, I wish u can tell me what commands should I run in the terminal？( Should I uninstall the opencv3 first ? )
my environment is (Ubuntu 16.04 anaconda3 python3.6) 
thanks for your reply

**Comment by jakirkham** [comment]
@jacktkk, this is not a support forum for `menpo`. Would encourage you to raise an issue with them on [their repo]( https://github.com/menpo/conda-opencv3 ) (assuming it is still supported). Alternatively you can try to use the `conda-forge` copy of `opencv`, which we would be more than happy to help with. Though would encourage you to raise a new issue after you have tried. Thanks.

**Comment by patricksnape** [comment]
Sorry @jakirkham that's my old repo - the menpo OpenCV build is no longer supported as I only support this repo - please remove the menpo opencv you have installed and install from conda-forge `conda install -c conda-forge opencv`
