### ISSUE TITLE
PY3K checking doesn't work (conda 4.3.23)

### ISSUE THREAD

**Issue by npbool** [conda-forge/opencv-feedstock#89]
https://github.com/conda-forge/opencv-feedstock/blob/f017e27dc3d9b9d3b84542d8470f3053d60ad03a/recipe/build.sh#L29

On conda 4.3.23, this checking won't pass when building with python3. Changing it to 
`if [ $PY3K ]; then` will solve the issue.

**Comment by msarahan** [comment]
I'm surprised this might be a conda bug. I would tend to look at conda
build for this bug. How did you isolate it to conda?

**Comment by patricksnape** [comment]
@npbool Is this actually still an issue?

**Comment by jakirkham** [comment]
Closing as I’m not really understanding how this is an issue. There seems to be confusion about `conda` vs. `conda-build`. Not to mention we have been using this check for some time to build the package without issues. Feel free to clarify the problem and we can revisit.
