### ISSUE TITLE
How to install a specific build of opencv:: py36

### ISSUE THREAD

**Issue by shravankumar147** [conda-forge/opencv-feedstock#93]
I am trying to install opencv for anaconda-python3.6. 
I have tried ` conda search opencv --channel conda-forge` and got a list of builds. 

> $ conda search opencv --channel conda-forge
> Fetching package metadata ...............
> opencv                       2.4.12              np110py27_1  conda-forge
>                              2.4.12              np111py27_1  conda-forge
>                              2.4.12              np111py27_2  conda-forge
>                              2.4.12              np110py27_2  conda-forge
>                              2.4.13              np112py27_0  conda-forge
>                              2.4.13              np111py27_0  conda-forge
>                              2.4.13              np112py27_1  conda-forge
>                              2.4.13              np111py27_1  conda-forge
>                              2.4.13              np113py27_1  conda-forge
>                              3.1.0               np110py35_0  conda-forge
>                              3.1.0               np111py34_0  conda-forge
>                              3.1.0               np110py27_0  conda-forge
>                              3.1.0               np111py35_0  conda-forge
>                              3.1.0               np111py27_0  conda-forge
>                              3.1.0               np110py34_0  conda-forge
>                              3.1.0               np112py35_1  conda-forge
>                              3.1.0               np111py27_1  conda-forge
>                              3.1.0               np110py27_1  conda-forge
>                              3.1.0               np112py36_1  conda-forge
>                              3.1.0               np110py35_1  conda-forge
>                              3.1.0               np112py27_1  conda-forge
>                              3.1.0               np111py34_1  conda-forge
>                              3.1.0               np110py34_1  conda-forge
>                              3.1.0               np111py35_1  conda-forge
>                              3.1.0               np111py36_1  conda-forge
>                              3.2.0               np112py27_0  conda-forge
>                              3.2.0               np111py27_0  conda-forge
>                              3.2.0               np112py35_0  conda-forge
>                              3.2.0               np111py35_0  conda-forge
>                              3.2.0               np111py36_0  conda-forge
>                              3.2.0               np112py36_0  conda-forge
>                              3.2.0             np112py35_200  conda-forge
>                              3.2.0             np111py27_200  conda-forge
>                              3.2.0             np111py35_200  conda-forge
>                              3.2.0             np112py27_200  conda-forge
>                              3.2.0             np112py36_200  conda-forge
>                              3.2.0             np111py36_200  conda-forge
>                              3.2.0             np111py36_201  conda-forge
>                              3.2.0             np111py27_201  conda-forge
>                              3.2.0             np112py27_201  conda-forge
>                              3.2.0             np111py35_201  conda-forge
>                              3.2.0             np112py35_201  conda-forge
>                              3.2.0             np112py36_201  conda-forge
>                              3.2.0             np112py35_202  conda-forge
>                              3.2.0             np111py35_202  conda-forge
>                              3.2.0             np111py36_202  conda-forge
>                              3.2.0             np112py27_202  conda-forge
>                              3.2.0             np111py27_202  conda-forge
>                              3.2.0             np112py36_202  conda-forge
>                              3.2.0             np111py36_203  conda-forge
>                              3.2.0             np113py36_203  conda-forge
>                              3.2.0             np113py35_203  conda-forge
>                              3.2.0             np112py36_203  conda-forge
>                              3.2.0             np112py27_203  conda-forge
>                              3.2.0             np111py35_203  conda-forge
>                              3.2.0             np113py27_203  conda-forge
>                              3.2.0             np112py35_203  conda-forge
>                              3.2.0             np111py27_203  conda-forge
>                              3.2.0             np113py36_204  conda-forge
>                              3.2.0             np112py35_204  conda-forge
>                              3.2.0             np111py27_204  conda-forge
>                              3.2.0             np111py36_204  conda-forge
>                              3.2.0             np111py35_204  conda-forge
>                              3.2.0             np113py35_204  conda-forge
>                              3.2.0             np112py36_204  conda-forge
>                              3.2.0             np112py27_204  conda-forge
>                              3.2.0             np113py27_204  conda-forge
>                              3.3.0                  py35_200  conda-forge
>                              3.3.0                  py36_200  conda-forge
> 
> 

Here how can I install specifically  `3.2.0  np112py36_204  conda-forge`  version for my python3.6 on windows x64 machine.

**Comment by patricksnape** [comment]
`conda install -c conda-forge opencv=3.2.0=np112py36_204`
