### ISSUE TITLE
trying to use openCV with ipython .... (((

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/opencv-feedstock#99]
@ZieloneOczy commented on [Sun Dec 10 2017](https://github.com/conda-forge/staged-recipes/issues/4575)

hello! I am having a hard time trying to use openCV with ipython ... am I doing something wrong?

In [1]: import cv2
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c8ec22b3e787> in <module>()
----> 1 import cv2
ImportError: dlopen(/Users/robertalexander/anaconda/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/robertalexander/anaconda/lib/libopencv_hdf.3.2.0.dylib
  Reason: image not found

---

@jakirkham commented on [Mon Dec 11 2017](https://github.com/conda-forge/staged-recipes/issues/4575#issuecomment-350821670)

Transferring to the feedstock as the issue does not belong here.

**Comment by jakirkham** [comment]
Could you please include `conda env export` results for the environment where this occurred? Thanks.

**Comment by alexander8R** [comment]
In the end, I reinstalled everything including conda and it seems to work now. I dont know whether there was just one or even more things wrong .... but it seems to be ok now.

**Comment by jakirkham** [comment]
Glad to hear it. Thanks for the update.
